### ISSUE TITLE
Several issues with the Twitter-/Statusnet.API

### ISSUE THREAD

**Issue by annando** [friendica/friendica#11284]
See https://git.friendi.ca/lubuwest/Friendiqa/issues/26

- [X] api/statuses/friends_timeline: news have three user objects, all are the same even for retoots (in earlier versions friendica_autor was different from user) #11286
- [X] For all APIs: in_reply_to_status_id has a value which has no connection to other id in the conversation #11282
- [x] posts with embedded content: the images are not in the attachments as was the case in earlier versions (Cannot reproduce)
- [X] /api/favorites/create and /api/favorites/destroy don't seem to work #11282
- [X] mentions (for example !developers) don't work for a new post #11288
- [x] /api/friends/list,api/followers/list,api/followers/ids and /api/statuses/friends return {"users":[],"next_cursor":-1,"next_cursor_str":"-","previous_cursor":0,"previous_cursor_str":"0","total_count":0} and not a list of contacts #12392
- [X] api/friendships/incoming returns some id but I have no friendship requests in the web view. #11288
- [x] api/lists/list returns an empty array (Wasn't implemented before)
- [X] api/friendica/group_show returns the homepage #11282
- [X] api/friendica/photo returns the homepage #11282
- [X] api/friendica/notifications is now named api/friendica/notification #11282
- [X] api/friendica/events delivers an empty array #11282
- [x] Permissions not working in /api/statuses/update #12393

**Comment by annando** [comment]
Concerning the last open problems:
- Embedded content: I cannot reproduce it. From my side it seems to work fine
- friends list: Same like above. It seems to work fine here
- The `lists/list` endpoint has got no function. But in fact it behaves like the legacy code. In the old code this endpoint was a dummy as well: https://github.com/friendica/friendica/blob/2021.09/include/api.php#L3215-L3232
- For the permissions I need examples. The Twitter endpoint always used the default permission. Also in the old code there hadn't been no permission processing as well.

Summary: I think I will postpone all further pull requests to the next version. I think that the most important fixes had been applied.

**Comment by annando** [comment]
I haven't got any new experience with this. So I think that we can move this issue to the next milestone.
