### ISSUE TITLE
Frio: open tasks

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2552]
This is a list of several to todo's for frio
- [x] Translation in the Jot-Popup (Text, Permissions, Browser)
- [x] better selection (switch between tabs) styling in Jot popup on mobile (https://github.com/rabuzarus/frio/issues/11)
- [ ] better indication of remote connections (https://github.com/rabuzarus/frio/issues/6)
- [ ] Theme settings: Cleanup the the backround-image options (https://github.com/rabuzarus/frio/issues/8)
- [ ] Filebrowser in theme settings should only select pictures as background which are visible to all (https://github.com/rabuzarus/frio/issues/13)
- [x] js: edit posts - original jot div should be cached in a js variable as long the edit post jot is available/open 
- [ ] The caching needs also to be done for filtering contacts - /mod/contact - by textcomplete (after filtering we have to contact lists - one original and one with the filtered content - but only one is visible. But since they are using same ID's this isn't optimal (if we can't solve this with caching we should think about moving ID's to classes)
- [x] frio hovercard should be available on every contact mentions
- [ ] we need to find a way to make the original js filebrowser more flexible (at the the present state frio does have a copy of the original friendica js filebrowser which was modified to work with frio)
- [ ] Item_photo_menu isn't integrated completely (some points like block user should be available through hovercard - other point which are more thread related should be available through the post popup menu)
- [ ] contact_template.tpl contains the also template information for js - this should be realized in some other way to reduce code duplication
- [ ] contact_template.tpl relies on the string "Forum" of `$contact.account_type` - Since "Forum" is an already translated string it isn't optimal because it would only work if a translation of "forum" is "Forum" (I don't know if there are other translations)
- [x] remove implementation in templates for tinymce (and provide an ability to disable tinymce automatically if frio is the selected theme) since frio focuses on normal plaintext editor
- [ ] Theme Settings: provide a better way to disable fields which can't be overwritten because the scheme won't let you (https://github.com/rabuzarus/frio/issues/9)
- [ ] Theme Settings: disabled fields shouldn't overwrite the former values in the db
- [x] Advanced Profile -> advanced (needs translation)
- [ ] Advanced Profile -> advanced - first entry shouldn't have a `<hr>` (profile-separator)
- [x] implement post highlight (The effect when somebody is following a thread link)
- [ ] wall_thread.tpl is a very hacky solution - frio seperates optically between top-post and comments - we need a better solution which tells the template that this was the last comment so it can insert a closing div for the comment block (I think such like this have do be done in core) - Maybe something like the number of comments of a top-level-post + the number of the comment so we can have something like `{{if $cmt_nmb >= $total_nmb}}</div>{{/if}}` in the template
- [x] Network view: borders of shared content are generated through js (this will not applied on new content which is loaded through js -> autoload next page or new post through update) -> I'm not happy to solve this with js. This is something core should provide (shared content in an own div with a class "shared_content")
- [ ] many templates aren't available for frio
- [ ] cleaning style.css (remove unused css - some css for the nav come from the humhub project not all is really used in frio - I really would like to know if there exist a tool which lets you know which css parts aren't used)
- [x] posts of a specific contact (is part of /mod/contact) does have a page background because sectiontop all other pages are normal pages. But it should look like the normal network stream with a background only for the posts
- [x] Jot Modal - There are some cases where the default content `share` (if nothing is inserted in the text field) don't get removed (e.g. insert links or videos, automatically added forum mentions by the the permissions page) - It would be nice if @fabrixxm could have also a view on this
- [x] frio's page template none.php should be implemented in core (e.g. the login modal does make use of it and if a other theme is the default theme of the friendica node this breaks login because `mode=none` won't work

**Comment by annando** [comment]
Could you separate the "show stoppers" from the "nice to have" stuff?

**Comment by rabuzarus** [comment]
@annando I'm not good in telling what the showstoppers would be. It's a kind of question of how "perfect" it should be. It is usable but the the one or the other thing is more or less annoying. It's a question of how you use friendica and what quality you expect.
Maybe important things would be the translation and the missing templates (like contact edit or the the photo stuff and several others)

**Comment by annando** [comment]
For me showstoppers are things where functionality is missing - and where text is hardcoded so that it cannot be translated.

**Comment by rabuzarus** [comment]
OK I made a list from the above points which are showstoppers in my point of view:
- [ ] many templates aren't available for frio (especially the photo templates but also admin settings and the contact edit templates)
- [ ] Jot Modal - There are some cases where the default content share (if nothing is inserted in the text field) don't get removed (e.g. insert links or videos, automatically added forum mentions by the the permissions page) - It would be nice if @fabrixxm could have also a view on this
- [ ] frio's page template none.php should be implemented in core (e.g. the login modal does make use of it and if a other theme is the default theme of the friendica node this breaks login because `mode=none` won't work)

**Comment by Hypolite** [comment]
I just stumbled on a missing frio template for the Register page. The page is styled, but not according to the frio theme.

**Comment by rabuzarus** [comment]
yes there are some missing template files. You can have a look for all existent files in /view/templates. 
The existent frio specific template files are in /view/theme/frio/templates

**Comment by tobiasd** [comment]
I think frio is missing the "Apps" menu, some addons are using to hook into the menu structure.

**Comment by poVoq** [comment]
Would be nice if the look of the /directory page could be replicated for the /forumdirectory view. Right now the latter is quite ugly.

**Comment by rabuzarus** [comment]
@poVoq 
thanks for reporting but what you describe are two different issues.

The forumdirectory is an addon. And your issue is that it should support frio. Please create a new issue.

And the forum listing would be no frio specific feature. It would also affect the other themes. Please create also a new issue for this ;-)

**Comment by rabuzarus** [comment]
@tobiasd 
Frio isn't missing the `App` menu. `App` is in the user dropdown menu and directs you to the `app` module

**Comment by tobiasd** [comment]
Ah ok. The other themes add a separate drop down menu with all the registered apps in it. That confused me most likely.

**Comment by rabuzarus** [comment]
Yes - but Frio does have already problems with all its icons/shortcuts in the navbar, so I decided to put it in the user drop down menu

**Comment by hoergen** [comment]
If i cancel the the javascript URL it produces  wrong output like
![00_temp](https://user-images.githubusercontent.com/24474762/59489933-c2b4ce80-8e83-11e9-8e5b-d345e29f0c87.png)

Please add an option, that one can deactivate this automation and use the old "code style" way.

**Comment by MrPetovan** [comment]
What are the steps to "cancel the javascript URL"?

**Comment by hoergen** [comment]
Just click on the x on the top right corner
![00_temp](https://user-images.githubusercontent.com/24474762/59517045-efd4a180-8ec2-11e9-8ec4-b63871048ba1.png)

**Comment by MrPetovan** [comment]
I can't reproduce this issue as described, here's what I tried:

## Case 1a: All typed, no Enter press
1. Open a `[url]` tag.
2. Type a URL.
3. Close the `[/url]` tag.

**Result**: The preview doesn't even show up.

## Case 1b: All typed, Space press
1. Open a `[url]` tag.
2. Type a URL.
3. Press Space. The Link Preview shows up.
4. Click on the preview close button.
5. Close the `[/url]` tag.

**Result**: A space is expectedly added before the closing tag because I typed it. No new line added. Link is correctly parsed.

## Case 1c: All typed, Enter press
1. Open a `[url]` tag.
2. Type a URL.
3. Press Enter. The Link Preview shows up.
4. Click on the preview close button.
5. Close the `[/url]` tag.

**Result**: A new line is expectedly added before the closing tag because I typed it. Link is expectedly not parsed.

## Case 2: Pasted link
1. Open a `[url]` tag.
2. Paste a URL. The Link Preview shows up.
3. Click on the preview close button.
4. Close the `[/url]` tag.

**Result**: No new line were added before the closing tag. Link is correctly parsed.

Can you reproduce the issue with a fixed list of steps?

**Comment by hoergen** [comment]
bbcode autocompletion seems to be broken after my last update one hour ago ..

I created a post like this 
```
Text before blah blah 
[ol]
  [*] bla blubb - https://github.com/friendica/friendica/issues/2552 and https://www.ted.com/
  [*] bla blubb - https://www.heise.de/ and https://www.nachdenkseiten.de/
[/ol]

Text after blah blah
```

and it reproduces the same error .. see in your timeline and here https://horche.demkontinuum.de/display/2196d4ee-155d-03b8-9cc0-cd3092144363

**Comment by MrPetovan** [comment]
I tried pasting the text but no link preview showed up. How did you compose this post? Did you paste the URLs or type them?

The link you provided ends up in a page not found error.

**Comment by hoergen** [comment]
I composed the text just writing the text, pasting the urls, canceld the preview that is gnerated automatically typed again, pasted the next url, canceld the preview and so on.

The link is restricted. I think it dowsn't work by clicking from github. It would work with the magic auth from friendica. But you should see it in your timline, because I added access rights for you.

**Comment by MrPetovan** [comment]
Can you please boil down your example to the minimum needed for it to fail the way you showed? Does it have to be exactly 4 different URLs in the post? Does it have to be a list with exactly 2 items? Does it need text before and/or after the list? Did you type the `[url]` tag at any point?

**Comment by MrPetovan** [comment]
Ha, never mind, I'm able to reproduce the issue. When any naked link is last in the last row of a list, this happens, but it has nothing to do with link previews. Whether it is canceled or not, the tags show up. I'd say it's another issue with the autolinker regular expression.

**Comment by hoergen** [comment]
I didn't type [url] i just pasted the link

The following failed (i cancel  javascript preview) and click on preview

```
[ol]
[*] https://www.ted.com/#/
[/ol]
```

**Comment by MrPetovan** [comment]
Yeah, if you don't cancel the preview it sill fails.

**Comment by foss-** [comment]
It is probably fair to close this issue. If any open issues remain relevant from this list, please file them as separate issues, ideally on a one problem per issue basis.
