### ISSUE TITLE
[frio] iOS Add to Home Screen issues

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#2800]
This is a low priority bucket list of issues arising when one tries to add the URL of Friendica instance running the frio theme to an iOS Home Screen. Basically, I don't want to forget those bullet points until the day I have time to actually look into them if I ever do.
- [x] Tapping on any link leaves the controlless window Friendica opens when accessed from the home screen for a regular Safari window with an app switch animation. This issue probably is fixed by a correct `<meta>` tag configuration . (#2834)
- [x] If there are any Youtube video in the stream, a pop-up opens to ask to open the video in the Youtube app. If the user taps Yes, it switches to the Youtube app showing the correct video, but if the user tries to return to the Friendica webapp, the stream reloads, which loads the video, which switch back to Youtube since the pop-up choice is remembered. I've been unable to disable this automatic switch from the iPhone settings, and removing and re-adding Friendica on the home screen didn't erase the saved choice to switch to the Youtube app. This one probably isn't specific to the frio theme. **(Unable to reproduce)**
- [x] When the app goes to an external link in Safari, switching back to the Friendica app reloads the whole page, not just the stream like I thought in 2. It is highly inconvenient. **(Fixed in iOS 12.2)**
- [x]  Certain links (like "Like" and "Comment") trigger the internal link listener and make the page reload. Removing the href attribute would prevent further issue, however using buttons would be more appropriate. I intent to try both solutions. (#3204)
- [x] [frio] Focusing a form input will slightly zoom in. This is because Safari expects form input font size to be 16px, and will zoom smalle font sizes. (#5668)
- [x] The image browser on frio is unusable: Tapping on an image to insert it in a message ~~or uploading a new one both~~ reload the page without any other effect. (#6381)
- [x] If you try to change what theme you use, the accordion-style controller it shows doesn’t work when clicked. So if you try to expand the “theme” section, the page reloads. (#6381)
- [x] Adding Friendica to Home Screen opens it in a Safari tab since iOS 13. (#8315)
- [x] ~~[frio] Links in the notifications dropdown redirect to Safari, bypassing the workaround added in #2834~~ (Unable to reproduce).
- [ ] [frio] Clicking on any pseudonym will just refresh the page without going to the remote URL.

**Comment by Hypolite** [comment]
3. When going to an external link and switching back the app to Friendica, the whole page reloads (not just the stream).

**Comment by Hypolite** [comment]
Turns out 3. is a hard limitation on how the standalone mode works and can't be easily fixed.

**Comment by Hypolite** [comment]
New issue on frio: Certain links (like "Like" and "Comment") trigger the internal link listener and make the page reload. Removing the href attribute would prevent further issue, however using buttons would be more appropriate. I intent to try both solutions.

**Comment by Hypolite** [comment]
New issue on frio: Clicking on any pseudonym will just refresh the page without going to the remote URL.

**Comment by MrPetovan** [comment]
I just added the frio image browser issue, it is completely unusable.

**Comment by xukashi** [comment]
with me, the window just closes as soon as I select a photo

**Comment by MrPetovan** [comment]
With no reload of the network stream page?

**Comment by MrPetovan** [comment]
No problem, I was just curious, it's an issue either way.

**Comment by divnull** [comment]
Trying this feature of iOS with a recent Friendica instance has some more problems than those mentioned above. Anything that brings up a “popup” type UI (such as clicking on a user’s name in a comment) doesn’t bring up that popup and appears to force a full page reload (smells like some default error handling fallback?).

**Comment by MrPetovan** [comment]
Since the last iOS update version 12.2, coming back from an app switch (with an external link for example) doesn’t refresh back the network page! 🎉

**Comment by annando** [comment]
@MrPetovan since I don't have an iPhone: Does this now work for you?

**Comment by MrPetovan** [comment]
There's a new setback since version 13: iOS doesn't recognize Friendica as a PWA, and as such adding Friendica to the Home Screen now just opens Friendica in a Safari tab. Pushing issue for the next milestone.

**Comment by AlfredSK** [comment]
Btw. same (just opens new tab) happens with FF on Android. But it works very well with Chrome on Android.

**Comment by annando** [comment]
PWA do work again with Friendica. So is it now fixed?

**Comment by AlfredSK** [comment]
I can confirm it works with FF on Android now. I have no iOS to check that too.

**Comment by MrPetovan** [comment]
@annando See the check list, there's a lingering issue with pseudonym links.

**Comment by annando** [comment]
@MrPetovan I guess it's the same with this milestone?

**Comment by MrPetovan** [comment]
Yep.

**Comment by foss-** [comment]
Followup for the remaining issue is https://github.com/friendica/friendica/issues/13340
