### ISSUE TITLE
Security: Migrate password hashing to password_hash()

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#3942]
Starting from version 5.5.0, PHP provides password hashing functions that is algorithm-independent, meaning that as stronger hashing algorithms make their way into the PHP core, the same code will seamlessly use it.

However, the transition from the current algorithm will be tricky because passwords can't be mass-migrated, we will need to keep track of who migrated their password through a successful login and who didn't yet.

Thankfully, people thought about this problem before us and wrote a blog post about it => https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#legacy-hashes

Related to #3946

Steps:
- [x] Centralize user login (#3970)
- [x] Move include/user function to src (#4003)
- [x] Centralize password update (#4285)
- [ ] Add new DB fields for migration, hashing the legacy hashes and changing login to support those as well as update to the new hash. (#4293)

Shout out to @paragonie-scott without whom this wouldn't have been possible.

**Comment by tobiasd** [comment]
What is with PHP 5.4 (which we support)?

**Comment by MrPetovan** [comment]
It doesn’t have `password_hash()` functions. However, if 5.4 compatibility is required, we can use https://github.com/ircmaxell/password_compat
