### ISSUE TITLE
[2019.01] PHP Fatal error

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5913]
- [x] https://github.com/friendica/friendica/issues/5913#issue-369895722 `Uncaught Error: Call to a member function attributes() on null in src/Protocol/Diaspora.php`
- [x] https://github.com/friendica/friendica/issues/5913#issuecomment-431665210 `Uncaught ArgumentCountError: Too few arguments to function twitter_convert_share(), 3 passed in addon/twitter/twitter.php`
- [x] https://github.com/friendica/friendica/issues/5913#issuecomment-433268802 `Uncaught Error: Call to private method Friendica\Model\Item::deleteById()`
- [x] https://github.com/friendica/friendica/issues/5913#issuecomment-435649118 `Uncaught Friendica\Network\HTTPException\InternalServerErrorException: 'https://friendica.mrpetovan.com/search?tag=King s gambit' is not a fully qualified URL`
- [x] https://github.com/friendica/friendica/issues/5913#issuecomment-437628443 `Uncaught Error: Call to undefined method Friendica\Util\Strings::getTags()`
- [x] https://github.com/friendica/friendica/issues/5913#issuecomment-440942527 `Uncaught Friendica\\Network\\HTTPException\\InternalServerErrorException: 'https://MELD.de/https://squeet.me/search?tag=In-Ear-Ohrh\xc3\xb6rer' is not a fully qualified URL`
- [ ] https://github.com/friendica/friendica/issues/5913#issuecomment-450017405 `PHP Fatal error: Uncaught Error: Call to undefined method Friendica\App::get_curl_content_type() in /addon/mailstream/mailstream.php:167`

```
PHP Fatal error:  Uncaught Error: Call to a member function attributes() on null in src/Protocol/Diaspora.php:424
Stack trace:
#0 mod/receive.php(53): Friendica\\Protocol\\Diaspora::decodeRaw(Array, '<?xml version="...')
#1 index.php(363): receive_post(Object(Friendica\\App))
#2 {main}
```

**Comment by copiis** [comment]
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function twitter_convert_share(), 3 passed in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php on line 561 and exactly 4 expected in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php:1894
Stack trace:
#0 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(561): twitter_convert_share(Array, Array, '\xC2\xA1Escuchad! No ...')
#1 /home/users/zsemberi/www/friendica/src/Content/Text/BBCode.php(909): {closure}(Array, Array, '\xC2\xA1Escuchad! No ...', true)
#2 [internal function]: Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}(Array)
#3 /home/users/zsemberi/www/friendica/src/Content/Text/BBCode.php(911): preg_replace_callback('/(.*?)\\[share(....', Object(Closure), 'En breve, m\xC3\xA1s ...')
#4 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(562): Friendica\Content\Text\BBCode::convertShare('En breve, m\xC3\xA1s ...', Object(Closure))
#5 /home/users/zsemberi/www/friendica/src/Core/Addon.php(309): twitter in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php on line 1894
```

**Comment by MrPetovan** [comment]
Thanks for the report, a fix is on the way.

**Comment by copiis** [comment]
PHP Fatal error:  Uncaught Error: Call to private method Friendica\Model\Item::deleteById() from context 'Friendica\Worker\RemoveUser' in /home/users/zsemberi/www/friendica/src/Worker/RemoveUser.php:27
Stack trace:
#0 [internal function]: Friendica\Worker\RemoveUser::execute(150)
#1 /home/users/zsemberi/www/friendica/src/Core/Worker.php(364): call_user_func_array('Friendica\\Worke...', Array)
#2 /home/users/zsemberi/www/friendica/src/Core/Worker.php(254): Friendica\Core\Worker::execFunction(Array, 'RemoveUser', Array, true)
#3 /home/users/zsemberi/www/friendica/src/Core/Worker.php(101): Friendica\Core\Worker::execute(Array)
#4 /home/users/zsemberi/www/friendica/bin/worker.php(51): Friendica\Core\Worker::processQueue(false)
#5 {main}
  thrown in /home/users/zsemberi/www/friendica/src/Worker/RemoveUser.php on line 27

**Comment by MrPetovan** [comment]
Paging @annando

**Comment by copiis** [comment]
Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: 'https://friendica.mrpetovan.com/search?tag=King s gambit' is not a fully qualified URL, please use App->internalRedirect() instead in src/Core/System.php:251
Stack trace:
#0 mod/toggle_mobile.php(20): Friendica\Core\System::externalRedirect('https://friendi...')
#1 src/LegacyModule.php(68): toggle_mobile_init(Object(Friendica\App))
#2 src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init')
#3 [internal function]: Friendica\LegacyModule::init()
#4 src/App.php(1820): call_user_func(Array)
#5 index.php(15): Friendica\App->runFrontend()
#6 {main}
  thrown in src/Core/System.php on line 251

**Comment by MrPetovan** [comment]
Tripping on the spaces I gather. they aren't properly urlencoded.

**Comment by copiis** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\Util\Strings::getTags() in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php:1268
Stack trace:
#0 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(1490): twitter_expand_entities(Object(Friendica\App), 'We know we\xE2\x80\x99ll...', Object(stdClass), '')
#1 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(1589): twitter_createpost(Object(Friendica\App), 1, Object(stdClass), Array, false, false, false)
#2 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(1703): twitter_fetchparentposts(Object(Friendica\App), 1, Object(stdClass), Object(Abraham\TwitterOAuth\TwitterOAuth), Array)
#3 /home/users/zsemberi/www/friendica/addon/twitter/twitter_sync.php(30): twitter_fetchhometimeline(Object(Friendica\App), 1)
#4 /home/users/zsemberi/www/friendica/src/Core/Worker.php(367): twitter_sync_run(Array, 3)
#5 /home/users/zsemberi/www/friendica/src/Core/Worker.php(298): Friendica\Core\Worker::execFunction(Array, 'twitter_sync_ru...' in /home/users/zsemberi/www/friendica/addon/twitter/twitter.php on line 1268

**Comment by copiis** [comment]
PHP Fatal error:  Uncaught Friendica\\Network\\HTTPException\\InternalServerErrorException: 'https://MELD.de/https://squeet.me/search?tag=In-Ear-Ohrh\xc3\xb6rer' is not a fully qualified URL, please use App->internalRedirect() instead in  /friendica/src/Core/System.php:252\nStack trace:\n
#0  /friendica/src/App.php(1850): Friendica\\Core\\System::externalRedirect('https://MELD.de...')\n
#1  /friendica/src/App.php(1865): Friendica\\App->internalRedirect('https://squeet....')\n
#2  /friendica/mod/redir.php(41): Friendica\\App->redirect('https://squeet....')\n
#3  /friendica/src/LegacyModule.php(69): redir_init(Object(Friendica\\App))\n
#4  /friendica/src/LegacyModule.php(39): Friendica\\LegacyModule::runModuleFunction('init')\n
#5 [internal function]: Friendica\\LegacyModule::init()\n
#6  /friendica/src/App.php(1692): call_user_func(Array)\n
#7  /friendica/index.php(15): Friend...\n'

**Comment by copiis** [comment]
`PHP Fatal error: Uncaught Error: Call to undefined method Friendica\App::get_curl_content_type() in /home/users/meld/www/friendica/addon/mailstream/mailstream.php:167
Stack trace:
#0 /home/users/meld/www/friendica/addon/mailstream/mailstream.php(265): mailstream_do_images(Object(Friendica\App), Array, Array)
#1 /addon/mailstream/mailstream.php(345): mailstream_send(Object(Friendica\App), '<967eadf951d7f8...', Array, Array)
#2 /src/Core/Hook.php(196): mailstream_cron(Object(Friendica\App), NULL)
#3 /src/Worker/ForkHook.php(16): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'cron', Array, NULL)
#4 [internal function]: Friendica\Worker\ForkHook::execute('cron', Array, NULL)
#5 /src/Core/Worker.php(365): call_user_func_array('Friendica\\Worke...', Array)
#6 /src/Core/Worker.php(255): Friendica\Core\Worker::execFunction(Array, 'ForkHook', Array, true)
#7 /addon/mailstream/mailstream.php on line 167`

**Comment by AlfredSK** [comment]
I'm not sure. Looks like this one has been already reported and __fixed__? But I'm still getting this one...

````
PHP Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: '/profile/gehrke_test?tag=Umwelt' is not a fully qualified URL, please use App->internalRedirect() instead in /var/www/html/libranet/src/Core/System.php:276
Stack trace:
#0 /var/www/html/libranet/mod/toggle_mobile.php(20): Friendica\Core\System::externalRedirect('/profile/gehrke...')
#1 /var/www/html/libranet/src/LegacyModule.php(69): toggle_mobile_init(Object(Friendica\App))
#2 /var/www/html/libranet/src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init')
#3 [internal function]: Friendica\LegacyModule::init()
#4 /var/www/html/libranet/src/App.php(1727): call_user_func(Array)
#5 /var/www/html/libranet/index.php(13): Friendica\App->runFrontend()
#6 {main}
  thrown in /var/www/html/libranet/src/Core/System.php on line 276
````

**Comment by MrPetovan** [comment]
Closed for release, next release thread is #6421
