### ISSUE TITLE
[2019.01] PHP Notices

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5932]
Follow-up to #5470 

If you intend to fix specific Notice messages, please report back to this thread once you're done with your PR.

- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429896286 `Undefined index: request in src/Network/Probe.php` 
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429896514 `Undefined offset: 504 in addon/buffer/bufferapp.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429896895 `Undefined variable: items in src/Worker/Delivery.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429897149 `Undefined index: download_content_length in src/Util/ParseUrl.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429897524 `Undefined index: id in src/Protocol/Diaspora.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429897811 `Undefined variable: id in addon/statusnet/statusnet.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-429898039 `Undefined index: download_content_length in src/Util/ParseUrl.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-430037007 `Undefined index: photo in src/Protocol/ActivityPub/Receiver.php`
- [ ] https://github.com/friendica/friendica/issues/5932#issuecomment-430172067 `iconv(): Wrong charset, conversion from 'MS949' to 'UTF-8//TRANSLIT' is not allowed in src/Util/ParseUrl.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-430212972 `Undefined index: timezone in src/Protocol/Diaspora.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-431574853 `Array to string conversion in src/Database/DBA.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-431578069 `basename() expects parameter 1 to be string, array given in src/Model/Photo.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-431664298 `Array to string conversion in src/Database/DBA.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-431827199 `Undefined index: host in src/Util/Network.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-432092510 `Undefined index: object-type in src/Protocol/OStatus.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-432492412 `Undefined variable: lang in view/php/default.php`
- [ ] https://github.com/friendica/friendica/issues/5932#issuecomment-432606956 `Undefined property: stdClass::$annotation in addon/fromgplus/fromgplus.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-434215290 `Undefined index: @id in src/Model/APContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-435329950 `Undefined index: return_path in src/Module/Login.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-436101582 `Undefined index: register_policy in src/Protocol/PortableContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-436562945 `Undefined index: register_policy in src/Protocol/PortableContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-437349439 `Undefined index: host in src/Util/Network.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-437628471 `Undefined index: title in src/Content/Text/BBCode.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-441099327 `Trying to get property 'instance_with_ssl' of non-object in src/Model/GContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-441331690 `Undefined offset: 9001 in mod/admin.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-441356834 `Undefined index: host in src/Util/Network.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-441357304 `Undefined index: 0.9.0 in mod/admin.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-441475597 `Undefined index: title in src/Content/Text/BBCode.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-443634844 `Undefined index: metadata in src/Protocol/PortableContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-444729816 `Undefined index: REMOTE_ADDR in src/Worker/GProbe.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-446342095 `Undefined index: title in src/Content/Text/BBCode.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-446812421 `Undefined index: info in src/Protocol/PortableContact.php`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-447552289 `Undefined index: uri in /.../src/Protocol/OStatus.php`
- [ ] https://github.com/friendica/friendica/issues/5932#issuecomment-447938422 `Array to string conversion in .../src/Content/Text/BBCode.php on line 1119`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-449819625 `Undefined index: info in /src/Protocol/PortableContact.php on line 1378`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-449949670 `Trying to get property 'status' of non-object in /addon/jappixmini/jappixmini.php on line 669`
- [x] https://github.com/friendica/friendica/issues/5932#issuecomment-453897724 `Undefined offset: 1 in /var/www/friendica/src/Protocol/Email.php on line 517`

**Comment by MrPetovan** [comment]
Reported by @AlfredSK in https://github.com/friendica/friendica/issues/5470#issuecomment-423652448
````
Undefined index: confirm in .../src/Network/Probe.php on line 946
Undefined index: name in .../src/Network/Probe.php on line 950
Undefined index: notify in .../src/Network/Probe.php on line 947
Undefined index: otype in .../include/enotify.php on line 477
Undefined index: photo in .../src/Network/Probe.php on line 949
Undefined index: poll in .../src/Network/Probe.php on line 948
Undefined index: pubkey in .../src/Network/Probe.php on line 951
Undefined index: request in .../src/Network/Probe.php on line 945
Undefined index: uid in .../include/enotify.php on line 37
Undefined index: uid in .../include/enotify.php on line 40
Undefined index: verb in .../include/enotify.php on line 476
````

**Comment by MrPetovan** [comment]
Reported by @copiis in https://github.com/friendica/friendica/issues/5470#issuecomment-423745878
```
PHP Notice: Undefined offset: 504 in addon/buffer/bufferapp.php on line 133
```

**Comment by MrPetovan** [comment]
Reported by @copiis in https://github.com/friendica/friendica/issues/5470#issuecomment-428870383
```
PHP Notice: Undefined variable: items in src/Worker/Delivery.php on line 174
```

**Comment by MrPetovan** [comment]
Reported by @AlfredSK in https://github.com/friendica/friendica/issues/5470#issuecomment-428893398
````
Undefined index: download_content_length in .../src/Util/ParseUrl.php on line 144
Undefined index: photo in .../src/Protocol/ActivityPub/Receiver.php on line 434
Undefined index: shortcode in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 100
Undefined index: shortcode in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 99
Undefined index: static_url in .../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 100
Undefined variable: type in .../mod/parse_url.php on line 79
````

**Comment by MrPetovan** [comment]
Reported by @haraldh in https://github.com/friendica/friendica/issues/5470#issuecomment-429854954
```
PHP Notice:  Undefined index: id in src/Protocol/Diaspora.php on line 2143
```

**Comment by MrPetovan** [comment]
Reported by @haraldh in https://github.com/friendica/friendica/issues/5470#issuecomment-429855039
```
PHP Notice:  Undefined variable: id in addon/statusnet/statusnet.php on line 661
```

**Comment by MrPetovan** [comment]
Reported by @copiis in https://github.com/friendica/friendica/issues/5470#issuecomment-429873625
```
PHP Notice: Undefined index: download_content_length in src/Util/ParseUrl.php on line 144
```

**Comment by annando** [comment]
The one from @haraldh had recently been fixed by me.

**Comment by MrPetovan** [comment]
Nope, it appears you fixed a different notice in #749, this one is still valid.

**Comment by MrPetovan** [comment]
```
Notice:  Undefined index: photo in src/Protocol/ActivityPub/Receiver.php on line 464
Stack trace:
  1. {main}() index.php:0
  2. Friendica\Module\Inbox::rawContent() index.php:349
  3. Friendica\Protocol\ActivityPub\Receiver::processInbox() src/Module/Inbox.php:51
  4. Friendica\Protocol\ActivityPub\Receiver::processActivity() src/Protocol/ActivityPub/Receiver.php:110
  5. Friendica\Protocol\ActivityPub\Receiver::prepareObjectData() src/Protocol/ActivityPub/Receiver.php:288
  6. Friendica\Protocol\ActivityPub\Receiver::getReceivers() src/Protocol/ActivityPub/Receiver.php:171
  7. Friendica\Protocol\ActivityPub\Receiver::switchContacts() src/Protocol/ActivityPub/Receiver.php:443
  8. Friendica\Protocol\ActivityPub\Receiver::switchContact() src/Protocol/ActivityPub/Receiver.php:500
```

**Comment by copiis** [comment]
PHP Notice:  iconv(): Wrong charset, conversion from `MS949' to `UTF-8//TRANSLIT' is not allowed in /home/users/zsemberi/www/friendica/src/Util/ParseUrl.php on line 191

**Comment by copiis** [comment]
PHP Notice:  Undefined index: timezone in /home/users/zsemberi/www/friendica/src/Protocol/Diaspora.php on line 3441
PHP Notice:  Undefined index: timezone in /home/users/zsemberi/www/friendica/src/Protocol/Diaspora.php on line 3444

**Comment by MrPetovan** [comment]
I'm not sure what we can do about the `iconv()` error, it looks like it choked on an unsupported Korean encoding.

**Comment by annando** [comment]
AFAIK you cannot catch the notice from ``ìconv```.

**Comment by MrPetovan** [comment]
Then we're done here for the moment! 🎉

**Comment by copiis** [comment]
PHP Notice:  Array to string conversion in /home/users/zsemberi/www/friendica/src/Database/DBA.php on line 463

**Comment by MrPetovan** [comment]
Reported by @copiis in https://github.com/friendica/friendica/issues/5911#issuecomment-431574921
```
PHP Warning: basename() expects parameter 1 to be string, array given in src/Model/Photo.php on line 107
PHP Warning: parse_url() expects parameter 1 to be string, array given in src/Util/Network.php on line 96
```

**Comment by annando** [comment]
@MrPetovan That notice indicates some deeper problem. So we should find the root of this and we shouldn't simply sanitize the function calls.

**Comment by MrPetovan** [comment]
I have stack traces for those.

**Comment by annando** [comment]
Ah okay, so it's magic ...

**Comment by copiis** [comment]
PHP Notice:  Undefined index: host in /home/users/zsemberi/www/friendica/src/Util/Network.php on line 358\n'

**Comment by tobiasd** [comment]
Mails from the worker contained these
~~~~
PHP Notice:  Undefined index: object-type in /.../src/Protocol/OStatus.php on line 1531
PHP Notice:  Undefined index: uri in /.../src/Protocol/OStatus.php on line 1938
PHP Notice:  Undefined index: body in /.../src/Protocol/OStatus.php on line 1941
PHP Notice:  Undefined index: title in /.../src/Protocol/OStatus.php on line 1943
PHP Notice:  Undefined index: guid in /.../src/Protocol/OStatus.php on line 1952
PHP Notice:  Undefined index: id in /.../src/Protocol/OStatus.php on line 1955
PHP Notice:  Undefined index: created in /.../src/Protocol/OStatus.php on line 1961
PHP Notice:  Undefined index: edited in /.../src/Protocol/OStatus.php on line 1962
PHP Notice:  Undefined property: stdClass::$parts in /.../src/Protocol/Email.php on line 118
PHP Notice:  Undefined offset: 1 in /.../src/Protocol/Email.php on line 485
PHP Notice:  Undefined offset: 2 in /.../src/Protocol/Email.php on line 485
PHP Notice:  Undefined offset: 3 in /.../src/Protocol/Email.php on line 485
~~~~

**Comment by annando** [comment]
```PHP Notice:  Undefined variable: lang in /var/www/virtual/pirati.ca/htdocs/view/php/default.php on line 2```

**Comment by copiis** [comment]
PHP Notice:  Undefined property: stdClass::$annotation in /home/users/zsemberi/www/friendica/addon/fromgplus/fromgplus.php on line 523

**Comment by copiis** [comment]
PHP Notice:  Undefined index: @id in /home/users/zsemberi/www/friendica/src/Model/APContact.php on line 109

**Comment by annando** [comment]
```PHP Notice:  Undefined index: return_path in src/Module/Login.php on line 48```

**Comment by copiis** [comment]
PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /home/users/zsemberi/www/friendica/src/Util/Crypto.php on line 27

**Comment by copiis** [comment]
PHP Notice:  Undefined index: register_policy in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1378

**Comment by copiis** [comment]
PHP Notice:  Undefined index: register_policy in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1381

**Comment by MrPetovan** [comment]
Someone didn't update their develop node to the latest.

**Comment by copiis** [comment]
PHP Notice:  Undefined index: host in /home/users/zsemberi/www/friendica/src/Util/Network.php on line 364\n'
PHP Notice:  Undefined index: return_path in /home/users/zsemberi/www/friendica/src/Module/Login.php on line 48\n'

**Comment by copiis** [comment]
PHP Notice:  Undefined index: title in /home/users/zsemberi/www/friendica/src/Content/Text/BBCode.php on line 628

**Comment by copiis** [comment]
PHP Notice:  Trying to get property 'instance_with_ssl' of non-object in /friendica/src/Model/GContact.php on line 980
PHP Notice:  Trying to get property 'instance_address' of non-object in /friendica/src/Model/GContact.php on line 986
PHP Notice:  Trying to get property 'instance_address' of non-object in friendica/src/Model/GContact.php on line 988

**Comment by AlfredSK** [comment]
Notices for admin.php line 667:

````
[24-Nov-2018 00:39:56 Europe/Berlin] PHP Notice:  Undefined offset: 9001 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1376 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1394-gcc22a0b5+href-otp in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1395 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1404 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1408 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1421 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1426 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 0.9.0-1430 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 2.1 in /var/www/html/libranet/mod/admin.php on line 667
[24-Nov-2018 00:49:44 Europe/Berlin] PHP Notice:  Undefined index: 3ecdab0911e061ec569fcd616c756ece9782a71b in /var/www/html/libranet/mod/admin.php on line 667
````

**Comment by copiis** [comment]
PHP Notice:  Undefined index: host in /friendica/src/Util/Network.php on line 365\n'

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: 0.9.0 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1376 in  /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1394-gcc22a0b5+href-otp in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1395 in  /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1408 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1421 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1426 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1428 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1430 in  /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1432 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1452 in  /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1477 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 0.9.0-1524 in /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 2.1 in  /friendica/mod/admin.php on line 667\nPHP message: 
PHP Notice:  Undefined index: 3ecdab0911e061ec569fcd616c756ece9782a71b in /friendica/mod/admin.php on line 667\n', referer: https://meld.de/admin/`

**Comment by copiis** [comment]
---
PHP Notice:  Undefined index: title in /src/Content/Text/BBCode.php on line 629
---

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: metadata in /friendica/src/Protocol/PortableContact.php on line 820`

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: REMOTE_ADDR in /friendica/src/Worker/GProbe.php on line 38`

**Comment by copiis** [comment]
`PHP Notice: Undefined index: title in /friendica/src/Content/Text/BBCode.php on line 629`

not fixed

**Comment by copiis** [comment]
> PHP Notice: Undefined index: info in /src/Protocol/PortableContact.php on line 1378
PHP Notice: Undefined index: register_policy in /src/Protocol/PortableContact.php on line 1381
PHP Notice: Undefined index: platform in /src/Protocol/PortableContact.php on line 1386

**Comment by MrPetovan** [comment]
Split from https://github.com/friendica/friendica/issues/5932#issuecomment-432092510
```
PHP Notice:  Undefined index: uri in /.../src/Protocol/OStatus.php on line 1938
PHP Notice:  Undefined index: body in /.../src/Protocol/OStatus.php on line 1941
PHP Notice:  Undefined index: title in /.../src/Protocol/OStatus.php on line 1943
PHP Notice:  Undefined index: guid in /.../src/Protocol/OStatus.php on line 1952
PHP Notice:  Undefined index: id in /.../src/Protocol/OStatus.php on line 1955
PHP Notice:  Undefined index: created in /.../src/Protocol/OStatus.php on line 1961
PHP Notice:  Undefined index: edited in /.../src/Protocol/OStatus.php on line 1962
```

@annando, what should happen if the above array indices are missing in `OStatus::entryContent` (line numbers are invalid now)?

**Comment by AlfredSK** [comment]
Some array to string conversion:

`PHP Notice:  Array to string conversion in .../src/Content/Text/BBCode.php on line 1119`

**Comment by copiis** [comment]
```
PHP Notice: Undefined index: info in /src/Protocol/PortableContact.php on line 1378
PHP Notice: Undefined index: register_policy in /src/Protocol/PortableContact.php on line 1381
PHP Warning: constant(): Couldn't find constant in /src/Protocol/PortableContact.php on line 1381
PHP Notice: Undefined index: platform in /src/Protocol/PortableContact.php on line 1386
```

**Comment by copiis** [comment]
`PHP Notice: Trying to get property 'status' of non-object in /addon/jappixmini/jappixmini.php on line 669`

**Comment by MrPetovan** [comment]
> `PHP Notice: Uninitialized string offset: 0 in /src/Worker/Notifier.php on line 148`

Same question as https://github.com/friendica/friendica/issues/5911#issuecomment-450002696, what version were you on when this notice showed up?

**Comment by MrPetovan** [comment]
Ping @annando https://github.com/friendica/friendica/issues/5932#issuecomment-447552289

**Comment by MrPetovan** [comment]
From #6443 by @AndyHee
> ```
> PHP Notice:  Undefined offset: 1 in /var/www/friendica/src/Protocol/Email.php on line 517
> PHP Notice:  Undefined offset: 0 in /var/www/friendica/src/Protocol/Email.php on line 578
> PHP Notice:  Undefined offset: 0 in /var/www/friendica/src/Protocol/Email.php on line 590
> ```

**Comment by MrPetovan** [comment]
Closed for release, next release thread is #6338
