### ISSUE TITLE
[2019.03] PHP Warnings

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6337]
- [x] https://github.com/friendica/friendica/issues/6337#issuecomment-450430381 `Illegal string offset 'created' in Worker/Notifier`
- [x] https://github.com/friendica/friendica/issues/6337#issuecomment-456403983 `A non-numeric value encountered in Core/Update`
- [x] https://github.com/friendica/friendica/issues/6337#issuecomment-467111446 `strlen() expects parameter 1 to be string, array given in .../mod/network.php on line 553`
- [x] https://github.com/friendica/friendica/issues/6337#issuecomment-468839548 `count(): Parameter must be an array or an object that implements Countable in .../include/api.php on line 956`
- [x] https://github.com/friendica/friendica/issues/6337#issuecomment-470733015 `Creating default object from empty value in .../mod/match.php on line 83`

**Comment by fabrixxm** [comment]
`PHP Warning:  A non-numeric value encountered in /home/kirgroup/htdocs/www/src/Core/Update.php on line 102`

**Comment by copiis** [comment]
`PHP Warning:  proc_close() has been disabled for security reasons in /friendica/src/App.php on line 1179\n', referer: https://xoyon.net/network`

**Comment by MrPetovan** [comment]
`proc_close()` is disabled but not `proc_open`?

**Comment by copiis** [comment]
> `proc_close()` is disabled but not `proc_open`?

Yes proc_close is disabled by default and I activated proc_open because it is supposed to be used by Friendica.

**Comment by copiis** [comment]
Just happened ...

**Comment by copiis** [comment]
```
PHP Warning:  file_put_contents( /friendica/proxy/https://MELD.de/photo/64749034215ac74fd0ba0bd144670564-5.png?ts=1530922563:thumb): failed to open stream: No such file or directory in /friendica/src/Module/Proxy.php on line 137\n'
 PHP Warning:  require( /friendica/vendor/composer/../divineomega/password_exposed/src/PasswordExposedFunction.php): failed to open stream: No such file or directory in /friendica/vendor/composer/autoload_real.php on line 70\n', referer: https://meld.de/search?search=openstreetmap&save=Save
 PHP Warning:  require( /friendica/vendor/composer/../divineomega/password_exposed/src/PasswordExposedFunction.php): failed to open stream: No such file or directory in /friendica/vendor/composer/autoload_real.php on line 70\n', referer: https://meld.de/profile/chebourne
```

**Comment by MrPetovan** [comment]
Please run `bin/composer.phar install --no-dev`.

**Comment by copiis** [comment]
`HP Warning:  Friendica\\Content\\Text\\HTML::toPlaintext(): unterminated entity reference A option to ask questions! \r \\*\xc2\xa0Learn by doing - Take advantage of Scrimba by frequently pausing the lesson and playing with the code. Then try to build things from your own computer using the stuff you just learned. And don\xca\xbct skip the practices! \r \\*\xc2\xa0Spaced learning and repetition is key - Give yourself time (days/weeks) to finish this course, and include lots of breaks. Don\xca\xbct try cramming it all in. in /friendica/src/Content/Text/HTML.php on line 584\n'`

**Comment by copiis** [comment]
```
PHP Warning:  file_put_contents(/friendica/proxy/https://MELD.de/photo/1d8e353ef6b1cb6d8afacc69d93cfbea-5.png?ts=1531126166): failed to open stream: No such file or directory in /friendica/src/Module/Proxy.php on line 119\n
PHP Warning:  file_put_contents(/friendica/proxy/https://MELD.de/photo/1d8e353ef6b1cb6d8afacc69d93cfbea-5.png?ts=1531126166:thumb): failed to open stream: No such file or directory in /friendica/src/Module/Proxy.php on line 137\n'
```

**Comment by copiis** [comment]
```
PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 261\nPHP message: PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 262\n
PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 263\nPHP message: PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 264\n'
```

**Comment by MrPetovan** [comment]
Have you switched storage backend on your node?

**Comment by copiis** [comment]
> Have you switched storage backend on your node?

No, just done a git pull today

**Comment by copiis** [comment]
```
PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\n', referer: https://meld.de/settings/display

PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40\nPHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45\n', referer: https://meld.de/community
```

**Comment by copiis** [comment]
```
PHP Warning: openssl_private_decrypt(): key parameter is not a valid private key in /friendica/src/Protocol/DFRN.php on line 1294 
PHP Warning: openssl_private_decrypt(): key parameter is not a valid private key in /friendica/src/Protocol/DFRN.php on line 1295 
```

**Comment by MrPetovan** [comment]
For https://github.com/friendica/friendica/issues/6337#issuecomment-458033153, can you please attach the relevant lines of the compiled Smarty file?

**Comment by fabrixxm** [comment]
first I would try to clear smarty3 compiled files. just to be sure they are up to date...

**Comment by MrPetovan** [comment]
I don't think it's a stale cache issue, from my experience files are recompiled immediately after source template files have been changed.

**Comment by copiis** [comment]
> PHP Warning: openssl_private_decrypt(): key parameter is not a valid private key in /friendica/src/Protocol/DFRN.php on line 1294 
> PHP Warning: openssl_private_decrypt(): key parameter is not a valid private key in /friendica/src/Protocol/DFRN.php on line 1295

If this message comes then the page is not accessible.

**Comment by MrPetovan** [comment]
Without a full trace this is impossible to debug, unless you have a specific page where this happens all the time.

**Comment by rabuzarus** [comment]
Since 3 years I want to report that my php.out is very often full of  
`[06-Feb-2019 15:13:32 Europe/Berlin] PHP Warning:  Illegal string offset 'share' in /var/www/vhosts/hosting107240.a2f21.netcup.net/httpdocs/friendica/view/smarty3/compiled/2f2d2313a8a2fa1c6b3dce7e39b2642b6267c76f_2.file.wall_thread.tpl.php on line 156`

**Comment by AlfredSK** [comment]
A brand new warning:
````
PHP Fatal error:  Uncaught Error: Class 'Friendica\Model\Logger' not found in ..../src/Model/Term.php:223
````

**Comment by MrPetovan** [comment]
That's a fatal error, not a warning => #6386

**Comment by AlfredSK** [comment]
Oops.

**Comment by AlfredSK** [comment]
But this time it is a warning:

`PHP Warning:  strlen() expects parameter 1 to be string, array given in .../mod/network.php on line 553`

**Comment by MrPetovan** [comment]
I'm pleasantly surprised by your newfound ability to stop trying to put a round peg in a square hole!

**Comment by MrPetovan** [comment]
> ```
> PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 40
> PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /friendica/view/smarty3/compiled/462ab9a1cdb3e7813101b547424e5eb5280f8d61_2.file.wall_thread.tpl.php on line 45
> ```

@copiis I don't have the same compiled version of `wall_thread.tpl` as you do, you'll have to provide your own version for us to be able to fix this. the origin theme is also important.

**Comment by AlfredSK** [comment]
Look! A warning.

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../include/api.php on line 956`

**Comment by AlfredSK** [comment]
Here's another one:
`PHP Warning:  Creating default object from empty value in .../mod/match.php on line 83`

**Comment by AlfredSK** [comment]
I'm getting those 'unterminated entity reference' errors pretty often. What's really weird about those errors they are not producing a clean stack trace. Some lines are dropped from PHP error log and sometimes lines are magically overwritten when looking into the issue (it's like a quantum effect: when you look at it the result is changing). :-) But I'm wrong.

In fact a Friendica code block itself is making the trouble. The PHP log looks weird because we're dealing with an issue related to an issue someone reported by using a code block. I know that sounds complicated. :-)

Have a look at this line of my PHP error log (containing real PHP error data and parts of the post that triggered the warning:

`[16-Mar-2019 14:07:26 UTC] PHP Warning:  Friendica\Content\Text\HTML::toPlaintext(): unterminated entity reference &amp; uti...')^M#2 /home/friendica/friendica/src/Content/Text/BBCode.php(1321): text_highlight('git pull &amp;&amp; uti...', 'sh')^M#3 [internal function]: Friendica\Content\Text\BBCode::textHighlightCallback(Array)^M#4 /home/friendica/friendica/src/Content/Text/BBCode.php(1423): preg_replace_callback('/\\[code=(.*?)\\]...', 'self::textHighl...', 'basically my up...')^M#5 /home/friendica/friendica/include/text.php(1430): Friendica\Content\Text\BBCode::convert('basically my up...')^M#6 /home/friendica/friendica/include/text.php(1213): prepare_text('basically my up...')^M#7 /home/friendica/friendica/src/Model/Item.php(686): put_ in /home/friendica/friendica/vendor/pear/text_highlighter/Text/Highlighter/Renderer/Array.php on line 154 in ........../src/Content/Text/HTML.php on line 584`

Everything related to '/home/friendica/friendica/...' is part of the post/comment not related to the actual path of my node.

I have seached the forum node (yeah! full text search) and could pin it down to that comment:
https://forum.friendi.ca/display/fd59d1fe175a885155dcae5919334318

Has the issue something to do with that `&amp;` in the first line?

Is this 'unterminated entity reference' bad? I mean 'unterminated' sounds like a serious issue when a HTML parser is involved. Could this be exploited in a bad way?

**Comment by AlfredSK** [comment]
```
[19-Mar-2019 18:49:35 UTC] PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in ..../libranet/mod/parse_url.php on line 29
```

**Comment by MrPetovan** [comment]
Closed for release, open issues have been moved to #6917
