### ISSUE TITLE
[2019.03] PHP Notices

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6338]
Core:
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-450430705 `Uninitialized string offset: 0 in src/Worker/Notifier.php on line 148`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-455785854 `Undefined index: uri in src/Protocol/OStatus.php on line 1938`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-456829992 `Undefined variable: micropro in src/Content/Widget/ContactBlock.php on line 110`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-456838079 `Undefined property: DOMNodeList::$item in src/Protocol/DFRN.php on line 2591`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-456839092 `Undefined index: avatar in src/Protocol/DFRN.php on line 2454`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-457099115 `Undefined index: id in /friendica/src/Protocol/OStatus.php`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-457900635 `Undefined variable: remoteUser in view/theme/frio/theme.php`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-457912040 `Undefined offset: 0 in view/theme/frio/theme.php`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-458030934 `Undefined variable: item_parent_uri in mod/display.php on line 286`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-460810667 `Undefined index: addr in src/Object/Post.php on line 790`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-462101779 `Undefined offset: 0 in mod/friendica.php on line 40`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-462722599 `Undefined index: name in src/Protocol/DFRN.php on line 769`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-464912016 `Undefined index: frio_bg_image_option in view/theme/frio/config.php on line 45`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466664417 `Undefined property: Friendica\App::$queue in src/Worker/Notifier.php`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466749280 `Trying to get property 'nodeValue' of non-object in src/Protocol/PortableContact.php on line 508`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466812104 `Undefined index: url in src/Protocol/ActivityPub/Processor.php on line 673`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466918220 `Undefined index: rel in src/Network/Probe.php on line 159`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466973949 `Only variables should be passed by reference in /src/Core/Worker.php on line 853`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-466973999 `Undefined index: after in /include/api.php on line 5349`
- [ ] https://github.com/friendica/friendica/issues/6338#issuecomment-472048378 `Undefined index: follow in .../src/Protocol/OStatus.php on line 1845`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-472048378 `Undefined variable: url in .../src/Network/Probe.php on line 356`
- [ ] https://github.com/friendica/friendica/issues/6338#issuecomment-472372364 `Undefined index: author in ...../src/Protocol/ActivityPub/Processor.php on line 285`
- [ ] https://github.com/friendica/friendica/issues/6338#issuecomment-472372364 `Undefined index: content in ...../src/Protocol/ActivityPub/Processor.php on line 298`
- [ ] https://github.com/friendica/friendica/issues/6338#issuecomment-472372364 `Undefined index: emojis in ...../src/Protocol/ActivityPub/Processor.php on line 299`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-472373099 `Undefined index: preamble in ...../include/enotify.php on line 458`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-473106117 `Array to string conversion in ...../view/theme/frio/php/default.php on line 60`

Addons:
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-458030934 `Undefined offset: 1 in addon/diaspora/Diaspora_Connection.php on line 49`
- [ ] https://github.com/friendica/friendica/issues/6338#issuecomment-458031433 `session_start(): A session had already been started - ignoring in addon/buffer/buffer.php on line 105`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-464912016 `Undefined index: irc-submit in /addon/irc/irc.php on line 58`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-464912016 `Undefined index: pageheader-submit in /addon/pageheader/pageheader.php on line 69`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-467121955 `Undefined index: Orientation in src/Object/Image.php on line 450`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-470681556 `Undefined index: term in mod/filerm.php on line 15`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-470681556 `Undefined index: url in mod/follow.php on line 63`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-470882973 `Undefined index: url in /mod/ping.php on line 284`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-471118589 `Array to string conversion in view/theme/frio/php/default.php on line 48`
- [x] https://github.com/friendica/friendica/issues/6338#issuecomment-472373099 `Undefined index: extension in ...../addon/js_upload/js_upload.php on line 336`

**Comment by MrPetovan** [comment]
Moved from https://github.com/friendica/friendica/issues/5932#issuecomment-449850545
```
PHP Notice: Uninitialized string offset: 0 in /src/Worker/Notifier.php on line 148
```

**Comment by MrPetovan** [comment]
Moved from https://github.com/friendica/friendica/issues/5932#issuecomment-447552289
```
PHP Notice:  Undefined index: uri in /.../src/Protocol/OStatus.php on line 1938
PHP Notice:  Undefined index: body in /.../src/Protocol/OStatus.php on line 1941
PHP Notice:  Undefined index: title in /.../src/Protocol/OStatus.php on line 1943
PHP Notice:  Undefined index: guid in /.../src/Protocol/OStatus.php on line 1952
PHP Notice:  Undefined index: id in /.../src/Protocol/OStatus.php on line 1955
PHP Notice:  Undefined index: created in /.../src/Protocol/OStatus.php on line 1961
PHP Notice:  Undefined index: edited in /.../src/Protocol/OStatus.php on line 1962
```

@annando, what should happen if the above array indices are missing in `OStatus::entryContent` (line numbers are invalid now)?

**Comment by annando** [comment]
This is in the function that generates a post. Since all important fields are missing, I would suggest quitting that function. We then have to check how to proceed.

**Comment by copiis** [comment]
`PHP Notice:  Undefined variable: micropro in /friendica/src/Content/Widget/ContactBlock.php on line 110\n'`

**Comment by copiis** [comment]
`PHP Notice:  Undefined property: DOMNodeList::$item in  /friendica/src/Protocol/DFRN.php on line 2591\nPHP message: PHP Notice:  Undefined property: DOMNodeList::$item in  /friendica/src/Protocol/DFRN.php on line 2606\n'`

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: avatar in  /friendica/src/Protocol/DFRN.php on line 2454\nPHP message: PHP Notice:  Undefined index: avatar in  /friendica/src/Protocol/DFRN.php on line 2462\n'`

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: id in /friendica/src/Protocol/OStatus.php on line 75\n'`

**Comment by annando** [comment]
@copiis should be solved now. Please refetch the current code.

**Comment by copiis** [comment]
PHP Notice:  Undefined index: id in /home/users/meld/www/friendica/src/Protocol/OStatus.php on line 75\n'

> @copiis should be solved now. Please refetch the current code.

Still coming in after git pull at 11:55

**Comment by copiis** [comment]
```
PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 261\nPHP message: PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 262\n
PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 263\nPHP message: PHP Notice:  Undefined variable: remoteUser in /friendica/view/theme/frio/theme.php on line 264\n'
```

**Comment by MrPetovan** [comment]
Oooh, this one is for @Ixiter.

**Comment by Ixiter** [comment]
Meeee .. this could have happened before #6527 was merged and user type =visitor.
The PHP notice first occurence is in line 261. `$remoteUser` ist used in line 262 the first time and was defined line 240 or line 246. ;) 
see [code](https://github.com/friendica/friendica/blob/develop/view/theme/frio/theme.php)

**Comment by copiis** [comment]
Well this still comes 5 minutes before

`PHP Notice:  Undefined offset: 0 in /friendica/view/theme/frio/theme.php on line 246\n'`

**Comment by Ixiter** [comment]
Ah .. ok .. got it. the sql query failed. Yeah, need to fix that.

**Comment by copiis** [comment]
`PHP Notice:  Undefined variable: item_parent_uri in /friendica/mod/display.php on line 286\n'`

**Comment by copiis** [comment]
`PHP Notice:  session_start(): A session had already been started - ignoring in /friendica/addon/buffer/buffer.php on line 105\nPHP message: PHP Notice:  Undefined index: oauth in /friendica/addon/buffer/bufferapp.php on line 126\nPHP message: PHP Notice:  Undefined variable: o in /friendica/addon/buffer/buffer.php on line 117\n', referer: https://meld.de/settings/connectors`

**Comment by copiis** [comment]
PHP Notice: Undefined offset: 1 in /friendica/addon/diaspora/Diaspora_Connection.php on line 49

**Comment by AlfredSK** [comment]
````
PHP Notice:  Undefined offset: 0 in .../mod/friendica.php on line 40
PHP Notice:  Undefined offset: 0 in .../mod/friendica.php on line 41
````

PHP 7.2.10

**Comment by ben-utzer** [comment]
New today. 

'[12-Feb-2019 11:28:21 Europe/Berlin] PHP Notice:  Undefined index: name in /srv/http/src/Protocol/DFRN.php on line 769
[12-Feb-2019 11:28:21 Europe/Berlin] PHP Notice:  Undefined index: url in /srv/http/src/Protocol/DFRN.php on line 770
[12-Feb-2019 11:28:21 Europe/Berlin] PHP Notice:  Undefined index: addr in /srv/http/src/Protocol/DFRN.php on line 771
[12-Feb-2019 11:28:21 Europe/Berlin] PHP Notice:  Undefined index: photo in /srv/http/src/Protocol/DFRN.php on line 781
'

**Comment by atasingorneq** [comment]
A new notice and no custom background image on the login page

`PHP Notice:  Undefined index: frio_bg_image_option in /html/view/theme/frio/config.php on line 45
`

and some more notes
`PHP Notice:  Undefined index: irc-submit in /addon/irc/irc.php on line 58`
`PHP Notice:  Undefined index: pageheader-submit in /addon/pageheader/pageheader.php on line 69`

**Comment by annando** [comment]
```Notice: Undefined property: Friendica\App::$queue in /path/to/friendica/src/Worker/Notifier.php on line 450```

**Comment by copiis** [comment]
```
PHP Notice: Trying to get property 'nodeValue' of non-object in /friendica/src/Protocol/PortableContact.php on line 508 
PHP Notice: Trying to get property 'nodeValue' of non-object in /friendica/src/Protocol/PortableContact.php on line 509 
```

**Comment by annando** [comment]
```
[24-Feb-2019 17:38:23 Europe/Berlin] PHP Notice:  Undefined index: url in /path/to/friendica/src/Protocol/ActivityPub/Processor.php on line 673
[24-Feb-2019 17:38:23 Europe/Berlin] PHP Notice:  Undefined index: nurl in /path/to/friendica/src/Protocol/ActivityPub/Processor.php on line 674
[24-Feb-2019 17:38:23 Europe/Berlin] PHP Notice:  Undefined index: alias in /path/to/friendica/src/Protocol/ActivityPub/Processor.php on line 675
```

**Comment by annando** [comment]
```
PHP Notice:  Undefined index: rel in /var/www/virtual/pirati.ca/htdocs/src/Network/Probe.php on line 159
```

**Comment by atasingorneq** [comment]
`PHP Notice: Only variables should be passed by reference in /src/Core/Worker.php on line 853`

**Comment by atasingorneq** [comment]
`PHP Notice:  Undefined index: after in /include/api.php on line 5349`

**Comment by realkinetix** [comment]
Via Php-FPM: PHP Notice:  Undefined index: Orientation in /home/friendica/friendica/src/Object/Image.php on line 450

**Comment by realkinetix** [comment]
PHP Notice:  Undefined index: term in /home/friendica/friendica/mod/filerm.php on line 15
PHP Notice:  Undefined index: url in /home/friendica/friendica/mod/follow.php on line 63

**Comment by atasingorneq** [comment]
`PHP Notice:  Undefined index: url in /mod/ping.php on line 284`
`PHP Notice:  Undefined index: micro in /mod/ping.php on line 285`

**Comment by AlfredSK** [comment]
Array to string conversion:

`[08-Mar-2019 23:24:08 UTC] PHP Notice:  Array to string conversion in .../view/theme/frio/php/default.php on line 48`

**Comment by AlfredSK** [comment]
PHP Notice:  Undefined index: follow in .../src/Protocol/OStatus.php on line 1845
PHP Notice:  Undefined variable: url in .../src/Network/Probe.php on line 356

**Comment by AlfredSK** [comment]
Some notices related to AP Processor:

```
[13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: author in ...../src/Protocol/ActivityPub/Processor.php on line 285
[13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: author in ...../src/Protocol/ActivityPub/Processor.php on line 286
[13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: content in ...../src/Protocol/ActivityPub/Processor.php on line 298
[13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: emojis in ...../src/Protocol/ActivityPub/Processor.php on line 299
```

**Comment by AlfredSK** [comment]
And two related to 'enotify' and addon 'js_upload':

```
[13-Mar-2019 09:50:56 UTC] PHP Notice:  Undefined index: preamble in ...../include/enotify.php on line 458
[13-Mar-2019 10:33:36 UTC] PHP Notice:  Undefined index: extension in ...../addon/js_upload/js_upload.php on line 336
```

**Comment by AlfredSK** [comment]
A new array to string conversion:

`PHP Notice:  Array to string conversion in ...../view/theme/frio/php/default.php on line 60`

**Comment by MrPetovan** [comment]
Closed for release, open issues have been moved to https://github.com/friendica/friendica/issues/6918

**Comment by copiis** [comment]
Geting this since a few days on -stable

```
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 228
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 256
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 320
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 333
```

**Comment by MrPetovan** [comment]
Please post this in #6918
