### ISSUE TITLE
Implicit mentions: Master issue list

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6676]
Follow-up to #6541
Follow-up to #6552

Second round of fixes. On the menu:
- [x] Fix incoming AP implicit mentions by recording implicit mentions (they were just discarded before, preventing the removal of further conversant mentions beyond the replied-to author) (#6726)
- [x] Add global config killswitch for implicit mentions (the existing config key only changed the behavior of incoming AP implicit mention removal) (#6726)
- [x] Fix Friendica-submitted items implicit mentions (Currently there aren't any implicit mentions) (#6726)
- [x] Fix potential issue with outgoing Diaspora implicit mentions (the top-level author may be mentioned instead of the replied-to author). (#6726)
- [x] Fix explicit mention default comment box text (Explicit mentions are sometimes missing from the comment box) (#6726)
- [x] Fix outgoing AP implicit mentions (we shouldn't add implicit self-mentions) (#6717)
- [x] Test new comment boxes collapse with explicit mentions (#6726)

**Comment by tobiasd** [comment]
I think implicit mentions should not be displayed at the bottom of the postings and comments, where explicit mentions are displayed.

**Comment by MrPetovan** [comment]
Indeed they shouldn't. I'm displaying them at the moment on my node for test purposes but I'm not planning on displaying them in the final PR.

**Comment by annando** [comment]
@MrPetovan this "item.parent-uri" instead of "item.thr-parent" is no issue while storing an item. Historically Friendica treated "item.parent-uri" like "item.thr-parent" during storing. Nowadays upon storing we simply are setting "item.parent-uri" to the value of "item.thr-parent" when that variable is set.

**Comment by MrPetovan** [comment]
Yes, I saw that, which meant using `parent-uri` wasn't warranted at all in the various protocols.

**Comment by MrPetovan** [comment]
Closed with #6726
