### ISSUE TITLE
[2019.06] PHP Fatal Errors

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6916]
Please report here any PHP Fatal error message obtained running the `2019.06` stable version.

- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-475459665 `Argument 1 passed to Core\ACL::getFullSelectorHTML() must be of the type array, null given`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-486411448 `require_once(): Failed opening required 'mod/nodeinfo.php'`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-487674639 `Argument 1 passed to Friendica\Protocol\ActivityPub\Processor::constructTagString() must be of the type array, null given`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-490134437 `Class 'Slim\Exception\NotFoundException' not found`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-494876901 `Argument 1 passed to Friendica\Module\BaseSearchModule::printResult()`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-495980051 `Argument 2 passed to Friendica\Content\Widget::postedByYear() must be of the type integer, null given`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-497054109 `Argument 1 passed to Friendica\Model\FileTag::fileToArray() must be of the type string, null given`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-500491695 `Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given`
- [x] https://github.com/friendica/friendica/issues/6916#issuecomment-500594062 `Argument 1 passed to Friendica\Util\Network::fetchUrl() must be of the type string, null given`

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/6386#issuecomment-471117954
> Some fatal error with stack trace concerning ACL:
>
>```
>[08-Mar-2019 21:51:34 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to >Friendica\Core\ACL::getFullSelectorHTML() must be of the type array, null given, called in >.../src/Module/Profile.php on line 207 and defined in .../src/Core/ACL.php:262
>Stack trace:
>#0 .../src/Module/Profile.php(207): Friendica\Core\ACL::getFullSelectorHTML(NULL, true)
>#1 [internal function]: Friendica\Module\Profile::content()
>#2 .../src/App.php(1359): call_user_func(Array)
>#3 .../index.php(17): Friendica\App->runFrontend()
>#4 {main}
>  thrown in .../src/Core/ACL.php on line 262
>```
### Discussion
@MrPetovan:
> Oof, this is a situation that should never happen where the session user id is set, but its record in the App isn't. I wouldn't even know where to start to debug this issue. How often does it turn out?

@AlfredSK:
> I had this today a couple of times. Maybe I triggered it myself when writing some test posts to a contact group I selected via ACL.
> I'll check the log again tomorrow and will see if I can reproduce the error.
> Hmm. Could not reproduce. PHP log is empty. 🎉 :-)
> I posted a private post (via ACL) again to the same contact group. No errors this time. 🤔
> I'll watch the log for some time...

**Comment by copiis** [comment]
> PHP Fatal error:  Uncaught TypeError: Argument 2 passed to geonames_load_config() must be an instance of Friendica\Util\Config\ConfigFileLoader, instance of Friendica\Core\Config\Cache\ConfigCacheLoader given, called in /friendica/src/Core/Hook.php on line 201 and defined in /friendica/addon/geonames/geonames.php:81
> Stack trace:
> #0 /friendica/src/Core/Hook.php(201): geonames_load_config(Object(Friendica\App), Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
> #1 /friendica/src/Core/Hook.php(177): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'load_config', Array, Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
> #2 /friendica/src/App.php(367): Friendica\Core\Hook::callAll('load_config', Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
> #3 /friendica/src/App.php(249): Friendica\App->reload()
> #4 /friendica/src/Factory/DependencyFactory.php(37): Friendica\App->__constru in /friendica/addon/geonames/geonames.php on line 81
>

**Comment by MrPetovan** [comment]
Please make sure you updated both friendica and addons to the latest `develop`.

**Comment by copiis** [comment]
I always update everything.
The message came only once, maybe the cronjob overlapped with the git pull.

**Comment by annando** [comment]
```
PHP Fatal error:  require_once(): Failed opening required 'mod/nodeinfo.php' (include_path='/path/to/friendica/vendor/pear/text_languagedetect:.:/usr/share/php:/var/path/to/friendica/include:/path/to/friendica/library:/var/www/virtual/pirati.ca/htdocs') in /path/to/friendica/src/Worker/CronJobs.php on line 27
```

**Comment by MrPetovan** [comment]
This needs to be cleaned up as #7033

**Comment by AlfredSK** [comment]
```
[29-Apr-2019 16:01:46 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Protocol\ActivityPub\Processor::constructTagString() must be of the type array, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 297 and defined in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php:68
Stack trace:
#0 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(297): Friendica\Protocol\ActivityPub\Processor::constructTagString(NULL, NULL)
#1 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(347): Friendica\Protocol\ActivityPub\Processor::processContent(Array, Array)
#2 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(213): Friendica\Protocol\ActivityPub\Processor::postItem(Array, Array)
#3 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(432): Friendica\Protocol\ActivityPub\Processor::createActivity(Array, 'http://purl.org...')
#4 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(110): Friendica\Protocol\ActivityPub\Receiver::processActivity in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 68
```

**Comment by MrPetovan** [comment]
@annando I'm unable to trace back in the ActivityPub where exactly we need to set a default value for the `tags` key of the `$activity` array to prevent the fatal error above. Can you please have a look?

**Comment by AlfredSK** [comment]
Another one:

```
[07-May-2019 14:01:46 UTC] PHP Fatal error:  Uncaught Error: Class 'Slim\Exception\NotFoundException' not found in ..../mod/cal.php:46
Stack trace:
#0 ..../src/LegacyModule.php(71): cal_init(Object(Friendica\App))
#1 ..../src/LegacyModule.php(40): Friendica\LegacyModule::runModuleFunction('init')
#2 [internal function]: Friendica\LegacyModule::init()
#3 ..../src/App.php(1212): call_user_func(Array)
#4 ..../index.php(17): Friendica\App->runFrontend()
#5 {main}
  thrown in ..../mod/cal.php on line 46
```

**Comment by MrPetovan** [comment]
Damn IDE autocomplete. I'll have a fix in the next 10 minutes.

**Comment by AlfredSK** [comment]
That was quick! :-)

**Comment by AlfredSK** [comment]
```
[16-May-2019 17:15:03 UTC] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Friendica\Protocol\ActivityPub\Processor::constructTagString() must be of the type array, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 304 and defined in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php:70 
Stack trace: 
#0 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(304): Friendica\Protocol\ActivityPub\Processor::constructTagString(NULL, NULL) 
#1 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(353): Friendica\Protocol\ActivityPub\Processor::processContent(Array, Array) 
#2 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(220): Friendica\Protocol\ActivityPub\Processor::postItem(Array, Array) 
#3 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(433): Friendica\Protocol\ActivityPub\Processor::createActivity(Array, 'http://purl.org...') 
#4 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(110): Friendica\Protocol\ActivityPub\Receiver::processActivity in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 70
```

**Comment by AlfredSK** [comment]
And...

```
[22-May-2019 13:26:11 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Module\BaseSearchModule::printResult() must be an instance of Friendica\Object\Search\ResultList, null given, called in .../src/Module/BaseSearchModule.php on line 73 and defined in .../src/Module/BaseSearchModule.php:87
Stack trace:
#0 .../src/Module/BaseSearchModule.php(73): Friendica\Module\BaseSearchModule::printResult(NULL, Object(Friendica\Content\Pager), '')
#1 .../src/Module/Search/Directory.php(30): Friendica\Module\BaseSearchModule::performSearch()
#2 [internal function]: Friendica\Module\Search\Directory::content()
#3 .../src/App.php(1247): call_user_func(Array)
#4 .../index.php(17): Friendica\App->runFrontend()
#5 {main}
  thrown in .../src/Module/BaseSearchModule.php on line 87
```

**Comment by AlfredSK** [comment]
Another one:

```
[23-May-2019 11:11:10 UTC] PHP Fatal error:  Uncaught Error: Class 'Friendica\Module\Register' not found in .../config/local-sample.config.php:37
Stack trace:
#0 {main}
  thrown in .../config/local-sample.config.php on line 37
```

**Comment by MrPetovan** [comment]
Looks like someone navigated directly to `/config/local-sample.config.php` on your website. Since this file doesn't call the Composer autoloader by itself, it choked on the class reference. Nothing to do here, no secret beans can be spilled this way anyway.

**Comment by AlfredSK** [comment]
The fatal ACL.php error from this https://github.com/friendica/friendica/issues/6916#issuecomment-475459665 happend again.
Do you need the new line numbers?

**Comment by MrPetovan** [comment]
Always.

**Comment by AlfredSK** [comment]
Here it is:

```
[24-May-2019 15:53:14 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Core\ACL::getFullSelectorHTML() must be of the type array, null given, called in /.../src/Module/Profile.php on line 215 and defined in /.../src/Core/ACL.php:262
Stack trace:
#0 /.../src/Module/Profile.php(215): Friendica\Core\ACL::getFullSelectorHTML(NULL, true)
#1 [internal function]: Friendica\Module\Profile::content()
#2 /.../src/App.php(1247): call_user_func(Array)
#3 /.../index.php(17): Friendica\App->runFrontend()
#4 {main}
  thrown in /.../src/Core/ACL.php on line 262
```

**Comment by MrPetovan** [comment]
Thanks!

**Comment by AlfredSK** [comment]
The fixed archive widget is throwing this...

```
[26-May-2019 08:23:31 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Friendica\Content\Widget::postedByYear() must be of the type integer, null given, called in .../src/Module/Profile.php on line 196 and defined in .../src/Content/Widget.php:458
Stack trace:
#0 .../src/Module/Profile.php(196): Friendica\Content\Widget::postedByYear('https://librane...', NULL, true)
#1 [internal function]: Friendica\Module\Profile::content()
#2 .../src/App.php(1247): call_user_func(Array)
#3 .../index.php(17): Friendica\App->runFrontend()
#4 {main}
  thrown in .../src/Content/Widget.php on line 458
```

**Comment by MrPetovan** [comment]
On it.

**Comment by MrPetovan** [comment]
@AlfredSK How about now?

**Comment by AlfredSK** [comment]
No fatal error anymore. Looks good. Good job! I'll do my best to find a new one for you. ;-)

**Comment by AlfredSK** [comment]
Since today a lot, a lot of this...

```
[29-May-2019 18:22:48 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Model\FileTag::fileToArray() must be of the type string, null given, called in /var/www/html/libranet/include/text.php on line 189 and defined in /var/www/html/libranet/src/Model/FileTag.php:106
Stack trace:
#0 /var/www/html/libranet/include/text.php(189): Friendica\Model\FileTag::fileToArray(NULL, 'category')
#1 /var/www/html/libranet/src/Object/Post.php(330): get_cats_and_terms(Array)
#2 /var/www/html/libranet/src/Object/Post.php(453): Friendica\Object\Post->getTemplateData(Array, 2)
#3 /var/www/html/libranet/src/Object/Thread.php(188): Friendica\Object\Post->getTemplateData(Array)
#4 /var/www/html/libranet/include/conversation.php(769): Friendica\Object\Thread->getTemplateData(Array)
#5 /var/www/html/libranet/src/Module/Profile.php(350): conversation(Object(Friendica\App), Array, Object(Friendica\Content\Pager), 'profile', 0, false, 'created', 3252)
#6 [internal function]: Friendica\Module\Profile::content()
#7 /var/www/html/libranet/src/App.php(1247): cal in /var/www/html/libranet/src/Model/FileTag.php on line 106
```

**Comment by annando** [comment]
After the last pulls I'm getting lot of errors and no post is delivered anymore:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Util/HTTPSignature.php on line 313 and defined in src/Util/Network.php:253
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Protocol/Diaspora.php on line 3145 and defined in src/Util/Network.php:253
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Protocol/DFRN.php on line 1470 and defined in src/Util/Network.php:253
```

**Comment by MrPetovan** [comment]
Caused by https://github.com/friendica/friendica/pull/7242

**Comment by nupplaphil** [comment]
> After the last pulls I'm getting lot of errors and no post is delivered anymore:
> 
> ```
> PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Util/HTTPSignature.php on line 313 and defined in src/Util/Network.php:253
> PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Protocol/Diaspora.php on line 3145 and defined in src/Util/Network.php:253
> PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Friendica\Util\Network::post() must be of the type string, array given, called in src/Protocol/DFRN.php on line 1470 and defined in src/Util/Network.php:253
> ```

That's what I was looking for.. Sorry that you got all these errors.. I'll fix them as soon as possible :-)
Caused by #7242

**Comment by annando** [comment]
@nupplaphil please don't just code and commit. Please test your changed system for some hours before committing, especially during the RC phase. Looking in the error logs is really crucial.

**Comment by nupplaphil** [comment]
Oh .. Sorry this wasn't intended .. 
=> Never trust your own phpdoc ..

**Comment by AlfredSK** [comment]
After the latest fixes I still get a fatal error:

```
[10-Jun-2019 21:02:08 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Util\Network::fetchUrl() must be of the type string, null given, called in /var/www/html/libranet/src/Model/Photo.php on line 416 and defined in /var/www/html/libranet/src/Util/Network.php:36
Stack trace:
#0 /var/www/html/libranet/src/Model/Photo.php(416): Friendica\Util\Network::fetchUrl(NULL, true)
#1 /var/www/html/libranet/src/Model/Contact.php(1720): Friendica\Model\Photo::importProfilePhoto(NULL, 0, 431738, true)
#2 /var/www/html/libranet/src/Model/APContact.php(233): Friendica\Model\Contact::updateAvatar(NULL, 0, 431738)
#3 /var/www/html/libranet/src/Protocol/ActivityPub.php(102): Friendica\Model\APContact::getByURL('https://mastodo...', true)
#4 /var/www/html/libranet/src/Network/Probe.php(349): Friendica\Protocol\ActivityPub::probeProfile('https://mastodo...')
#5 /var/www/html/libranet/src/Model/Contact.php(1337): Friendica\Network\Probe::uri('https://mastodo...', '', 0)
#6 /var/www/html/libranet/src/Protocol/DFRN.php(2392): Friendica\Model\Contact::g in /var/www/html/libranet/src/Util/Network.php on line 36
```

**Comment by annando** [comment]
@AlfredSK I'm at it. I'm just testing my fix over night.

**Comment by AlfredSK** [comment]
**Dropping a contact: white page of death + fatal error**

I'm getting an all white page and a fatal PHP error (with stack trace) when I drop/delete a contact. The white page shows this URL in the browser's URL bar:
https://libranet.de/contact/514418/drop?mode=none&_=1560977484705&confirmed=Yes

Interesting: Happens when **dropping AP contacts like Mastodon, Osada and Friendica (AP)** but not when dropping Friendica (DFRN) and Diaspora contacts.

Trace:
```
[19-Jun-2019 22:51:54 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Friendica\Util\Network::post() must be of the type string, null given, called in /var/www/html/libranet/src/Util/HTTPSignature.php on line 313 and defined in /var/www/html/libranet/src/Util/Network.php:253
Stack trace:
#0 /var/www/html/libranet/src/Util/HTTPSignature.php(313): Friendica\Util\Network::post(NULL, '{"@context":["h...', Array)
#1 /var/www/html/libranet/src/Protocol/ActivityPub/Transmitter.php(1647): Friendica\Util\HTTPSignature::transmit(Array, NULL, 2)
#2 /var/www/html/libranet/src/Model/Contact.php(734): Friendica\Protocol\ActivityPub\Transmitter::sendContactUndo('https://osada.u...', 514418, 2)
#3 /var/www/html/libranet/src/Module/Contact.php(256): Friendica\Model\Contact::terminateFriendship(Array, Array, true)
#4 /var/www/html/libranet/src/Module/Contact.php(472): Friendica\Module\Contact::dropContact(Array)
#5 [internal function]: Friendica\Module\Contact::content()
#6 /var/www/html/libranet/src/App.php(1241): call_user_func(Array)
#7 /var/www/html/l in /var/www/html/libranet/src/Util/Network.php on line 253
```

**Comment by MrPetovan** [comment]
Thank for the elaboration!

**Comment by MrPetovan** [comment]
Closed for release, onwards to https://github.com/friendica/friendica/issues/7297
