### ISSUE TITLE
[2019.06] PHP Warnings

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6917]
Please report here any PHP Warning message obtained running the 2019.06 stable version.

- [ ] https://github.com/friendica/friendica/issues/6917#issuecomment-475461079 `Text\HTML::toPlaintext(): unterminated entity reference &amp; in src/Content/Text/HTML.php on line 584`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-475461338 `hex2bin(): Hexadecimal input string must have an even length in mod/parse_url.php on line 29`
- [ ] https://github.com/friendica/friendica/issues/6917#issuecomment-475462285 `Illegal string offset 'share' in view/smarty3/compiled/2f...6f_2.file.wall_thread.tpl.php`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-481800767 `strpos() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 105`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-481800767 `substr() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 81`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-488724649 `openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended in .../mod/dfrn_confirm.php on line 197`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-492798238 `Input string must be hexadecimal string in .../mod/photos.php on line 1029`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-492798238 `Hexadecimal input string must have an even length in .../mod/photos.php on line 1029`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-494087890 `count(): Parameter must be an array or an object that implements Countable in .../mod/dfrn_request.php on line 479`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-500123485 `strlen() expects parameter 1 to be string, array given in .../src/Util/Network.php on line 99`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-500123485 `parse_url() expects parameter 1 to be string, array given in .../src/Util/Network.php on line 105`
- [x] https://github.com/friendica/friendica/issues/6917#issuecomment-501661530 `Invalid argument supplied for foreach() in /var/www/html/src/Network/Probe.php on line 202`

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/6337#issuecomment-473535594

> Have a look at this line of my PHP error log (containing real PHP error data and parts of the post that triggered the warning:
> 
> ```
> [16-Mar-2019 14:07:26 UTC] PHP Warning:  Friendica\Content\Text\HTML::toPlaintext(): unterminated entity reference &amp;
> "uti...')^M#2 /home/friendica/friendica/src/Content/Text/BBCode.php(1321): text_highlight('git pull &amp;&amp; uti...', 'sh')^M#3 [internal function]: Friendica\Content\Text\BBCode::textHighlightCallback(Array)^M#4 /home/friendica/friendica/src/Content/Text/BBCode.php(1423): preg_replace_callback('/\\[code=(.*?)\\]...', 'self::textHighl...', 'basically my up...')^M#5 /home/friendica/friendica/include/text.php(1430): Friendica\Content\Text\BBCode::convert('basically my up...')^M#6 /home/friendica/friendica/include/text.php(1213): prepare_text('basically my up...')^M#7 /home/friendica/friendica/src/Model/Item.php(686): put_ in /home/friendica/friendica/vendor/pear/text_highlighter/Text/Highlighter/Renderer/Array.php on line 154"
>  in ........../src/Content/Text/HTML.php on line 584
> ```
> 
> Everything related to '/home/friendica/friendica/...' is part of the post/comment not related to the actual path of my node.
> 
> I have seached the forum node (yeah! full text search) and could pin it down to that comment:
> https://forum.friendi.ca/display/fd59d1fe175a885155dcae5919334318
> 
> Has the issue something to do with that `&amp;` in the first line?
> 
> Is this 'unterminated entity reference' bad? I mean 'unterminated' sounds like a serious issue when a HTML parser is involved. Could this be exploited in a bad way?

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/6337#issuecomment-474547595

> ```
> [19-Mar-2019 18:49:35 UTC] PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in mod/parse_url.php on line 29
> ```

**Comment by MrPetovan** [comment]
From

Since 3 years I want to report that my php.out is very often full with  
```
[06-Feb-2019 15:13:32 Europe/Berlin] PHP Warning:  Illegal string offset 'share' in /var/www/vhosts/hosting107240.a2f21.netcup.net/httpdocs/friendica/view/smarty3/compiled/2f2d2313a8a2fa1c6b3dce7e39b2642b6267c76f_2.file.wall_thread.tpl.php on line 156
```

Comment from @MrPetovan : This is likely caused by this block: https://github.com/friendica/friendica/blob/39fc98f5f3fcfcac44a8e45596b3cda3c1535c61/view/theme/frio/templates/wall_thread.tpl#L346-L351

**Comment by AlfredSK** [comment]
2019.06-dev:
```
[10-Apr-2019 16:09:00 UTC] PHP Warning:  strpos() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 105
[10-Apr-2019 16:09:00 UTC] PHP Warning:  substr() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 105
```

**Comment by AlfredSK** [comment]
2019.06-dev:
```
[30-Apr-2019 17:40:58 UTC] PHP Warning:  openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended in .../mod/dfrn_confirm.php on line 197
```

**Comment by MrPetovan** [comment]
> 2019.06-dev:
> 
> ```
> [10-Apr-2019 16:09:00 UTC] PHP Warning:  strpos() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 105
> [10-Apr-2019 16:09:00 UTC] PHP Warning:  substr() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 105
> [25-Apr-2019 15:40:49 UTC] PHP Warning:  substr() expects parameter 1 to be string, array given in .../src/Protocol/ActivityPub/Processor.php on line 81
> ```

I believe this had to do with the change in Pleroma output to add the language metadata for each label, making strings into array. But I believe it was fixed with #7045. Let us know if you still see this message.

**Comment by MrPetovan** [comment]
> 2019.06-dev:
> 
> ```
> [30-Apr-2019 17:40:58 UTC] PHP Warning:  openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended in .../mod/dfrn_confirm.php on line 197
> ```

Ugh, cryptographic security issue. I don't know enough about it to suggest a more secure version while keeping the system working and ensure backwards compatibility with earlier versions. I might look into it just for the sake of it.

**Comment by annando** [comment]
@MrPetovan I'm working at it: https://github.com/annando/friendica/tree/ap-connect
Hopefully I will be done with this at the weekend.

**Comment by AlfredSK** [comment]
> I believe this had to do with the change in Pleroma output to add the language metadata for each label, making strings into array. But I believe it was fixed with #7045. Let us know if you still see this message.

That's possible. I'll watch the log if the message reappears.

**Comment by AlfredSK** [comment]
```
[15-May-2019 19:08:41 UTC] PHP Warning:  hex2bin(): Input string must be hexadecimal string in .../mod/photos.php on line 1029
[15-May-2019 19:08:53 UTC] PHP Warning:  hex2bin(): Hexadecimal input string must have an even length in .../mod/photos.php on line 1029
```

**Comment by AlfredSK** [comment]
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in .../mod/dfrn_request.php on line 479`

**Comment by copiis** [comment]
PHP Notice: Undefined index: protocol in /friendica/src/Worker/Notifier.php on line 444

**Comment by AlfredSK** [comment]
Some warning on Network.php:
```
[07-Jun-2019 22:57:40 UTC] PHP Warning:  strlen() expects parameter 1 to be string, array given in .../src/Util/Network.php on line 99
[07-Jun-2019 22:57:40 UTC] PHP Warning:  parse_url() expects parameter 1 to be string, array given in .../src/Util/Network.php on line 105
```

**Comment by nupplaphil** [comment]
Some new warnings on Probe.php:
```console
[12-Jun-2019 01:19:17 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/src/Network/Probe.php on line 202                                                                      
[12-Jun-2019 01:19:17 Europe/Berlin] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/html/src/Network/Probe.php:202) in /var/www/html/src/Core/System.php on line 250                                                                                                                                                                                                            
```

**Comment by MrPetovan** [comment]
Closed for release, onwards to https://github.com/friendica/friendica/issues/7298
