### ISSUE TITLE
[2019.06] PHP Notices

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#6918]
Please report here any PHP Notice message obtained running the `2019.06` stable version.

- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-475463093 `Undefined index: follow in src/Protocol/OStatus.php on line 1845`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-475463223 `Undefined index: author in src/Protocol/ActivityPub/Processor.php on line 285`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-480571782 ` Only variables should be passed by reference in /src/App.php on line 1273`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-481801346 `Array to string conversion in .../src/Protocol/ActivityPub/Processor.php on line 117`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-481801346 `Array to string conversion in .../src/Protocol/ActivityPub/Processor.php on line 54`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-489428958 `Undefined index: uid in src/Model/Contact.php on line 2385`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-491009954 `Undefined index: ident in .../mod/notifications.php on line 141`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-491009954 `Undefined index: ident in .../mod/notifications.php on line 322`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-491010539 `Undefined variable: a in .../src/Module/Help.php on line 102`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-491490533 `Only variables should be passed by reference in .../src/Module/Admin/Federation.php on line 90`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-491492826 `Undefined index: visitor_visiting in ...mod/redir.php on line 73`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-493515358 `Undefined index: item_id in .../mod/photos.php on line 1506` 
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-493515358 `Undefined index: item_id in .../mod/photos.php on line 1515` 
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-493515358 `Undefined index: author-network in .../include/conversation.php on line 1020` 
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-493515358 `Undefined index: XXXXX in .../src/Protocol/ActivityPub/Processor.php on line XXXXX`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-495198587 `Undefined index: href in /friendica/src/Protocol/PortableContact.php on line 675`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-495198587 `Undefined index: protocol in /friendica/src/Worker/Notifier.php on line 444`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-495928679 `Undefined variable: header in .../src/Module/Contact.php on line 782`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-497683633 `Undefined index: nickname in /friendica/addon/twitter/twitter.php on line 1886`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-498043239 `Undefined offset: 0 in .../src/Util/Crypto.php on line 212`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-498043313 `Undefined index: id in .../src/Model/Contact.php on line 2160`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-500123335 `Array to string conversion in .../src/Protocol/ActivityPub/Receiver.php on line 758`
- [ ] https://github.com/friendica/friendica/issues/6918#issuecomment-500123335 `Array to string conversion in .../src/Database/DBA.php on line 513`
- [x] https://github.com/friendica/friendica/issues/6918#issuecomment-501383962 `Undefined index: cid in /var/www/html/libranet/src/Model/Profile.php on line 325`

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/6338#issuecomment-472048378

> `PHP Notice:  Undefined index: follow in .../src/Protocol/OStatus.php on line 1845`

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/6338#issuecomment-472372364

> Some notices related to AP Processor:
> 
> ```
> [13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: author in ...../src/Protocol/ActivityPub/Processor.php on line 285
> [13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: author in ...../src/Protocol/ActivityPub/Processor.php on line 286
> [13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: content in ...../src/Protocol/ActivityPub/Processor.php on line 298
> [13-Mar-2019 06:50:59 UTC] PHP Notice:  Undefined index: emojis in ...../src/Protocol/ActivityPub/Processor.php on line 299
> ```

**Comment by atasingorneq** [comment]
Every few seconds this notice appears in the php-error.log:
`[07-Apr-2019 10:49:35 Europe/Berlin] PHP Notice:  Only variables should be passed by reference in /src/App.php on line 1273`

**Comment by AlfredSK** [comment]
2019.06-dev:
```
[10-Apr-2019 16:09:00 UTC] PHP Notice:  Array to string conversion in .../src/Protocol/ActivityPub/Processor.php on line 117
[10-Apr-2019 16:39:02 UTC] PHP Notice:  Array to string conversion in .../src/Protocol/ActivityPub/Processor.php on line 54
```

**Comment by annando** [comment]
Current 2019.06-dev:

```
Undefined index: uid in src/Model/Contact.php on line 2385
Undefined index: id in src/Model/Contact.php on line 2389
Undefined index: parent-guid in src/Protocol/DFRN.php on line 990
```

**Comment by AlfredSK** [comment]
Some notices related to notifications.php:
```
PHP Notice:  Undefined index: ident in .../mod/notifications.php on line 141
PHP Notice:  Undefined index: ident in .../mod/notifications.php on line 322
```

**Comment by AlfredSK** [comment]
...and two further notices related to Help.php:
```
PHP Notice:  Undefined variable: a in .../src/Module/Help.php on line 102
PHP Notice:  Trying to get property 'page' of non-object in .../src/Module/Help.php on line 102
```

**Comment by AlfredSK** [comment]
Maybe related to the latest changes to the admin module?

`PHP Notice:  Only variables should be passed by reference in .../src/Module/Admin/Federation.php on line 90`

**Comment by AlfredSK** [comment]
And...

`PHP Notice:  Undefined index: visitor_visiting in ...mod/redir.php on line 73`

**Comment by AlfredSK** [comment]
_Some_ further notices:

photos.php:
```
Undefined index: item_id in .../mod/photos.php on line 1506
Undefined index: item_id in .../mod/photos.php on line 1515
```

conversation.php:
```
Undefined index: author-network in .../include/conversation.php on line 1020
```

AP Processor.php:
```
Undefined index: author in .../src/Protocol/ActivityPub/Processor.php on line 334
Undefined index: author in .../src/Protocol/ActivityPub/Processor.php on line 335
Undefined index: published in .../src/Protocol/ActivityPub/Processor.php on line 348
Undefined index: updated in .../src/Protocol/ActivityPub/Processor.php on line 349
Undefined index: diaspora:guid in .../src/Protocol/ActivityPub/Processor.php on line 350
Undefined index: name in .../src/Protocol/ActivityPub/Processor.php on line 266
Undefined index: content in .../src/Protocol/ActivityPub/Processor.php on line 271
Undefined index: summary in .../src/Protocol/ActivityPub/Processor.php on line 295
Undefined index: tags in .../src/Protocol/ActivityPub/Processor.php on line 303
Undefined index: sensitive in .../src/Protocol/ActivityPub/Processor.php on line 303
Undefined index: location in .../src/Protocol/ActivityPub/Processor.php on line 305
Undefined index: generator in .../src/Protocol/ActivityPub/Processor.php on line 311
Undefined index: attachments in .../src/Protocol/ActivityPub/Processor.php on line 359
Undefined index: author in .../src/Protocol/ActivityPub/Processor.php on line 365
Undefined index: author in .../src/Protocol/ActivityPub/Processor.php on line 368
Undefined index: name in .../src/Protocol/ActivityPub/Processor.php on line 231
Undefined index: content in .../src/Protocol/ActivityPub/Processor.php on line 232
Undefined index: start-time in .../src/Protocol/ActivityPub/Processor.php on line 233
Undefined index: end-time in .../src/Protocol/ActivityPub/Processor.php on line 234
Undefined index: location in .../src/Protocol/ActivityPub/Processor.php on line 236
```

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: href in /friendica/src/Protocol/PortableContact.php on line 675`

**Comment by AlfredSK** [comment]
```
[25-May-2019 15:39:53 UTC] PHP Notice:  Undefined variable: header in .../src/Module/Contact.php on line 782
[25-May-2019 15:40:00 UTC] PHP Notice:  Undefined variable: header in .../src/Module/Contact.php on line 781
[25-May-2019 15:40:03 UTC] PHP Notice:  Undefined variable: header in .../src/Module/Contact.php on line 783
[25-May-2019 15:40:07 UTC] PHP Notice:  Undefined variable: header in .../src/Module/Contact.php on line 784
[25-May-2019 15:40:14 UTC] PHP Notice:  Undefined variable: header in .../src/Module/Contact.php on line 787
```

**Comment by copiis** [comment]
Still coming
`PHP Notice:  Undefined index: protocol in /friendica/src/Worker/Notifier.php on line 444`

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: nickname in /friendica/addon/twitter/twitter.php on line 1886`

**Comment by AlfredSK** [comment]
```
[02-Jun-2019 11:12:45 UTC] PHP Notice:  Undefined offset: 0 in .../src/Util/Crypto.php on line 212
[02-Jun-2019 11:12:45 UTC] PHP Notice:  Trying to get property 'asnData' of non-object in .../src/Util/Crypto.php on line 212
```

**Comment by AlfredSK** [comment]
...and:

```
[02-Jun-2019 13:46:04 UTC] PHP Notice:  Undefined index: id in .../src/Model/Contact.php on line 2160
```

**Comment by AlfredSK** [comment]
Some array to string conversions in AP Receiver:

```
[07-Jun-2019 22:57:40 UTC] PHP Notice:  Array to string conversion in .../src/Protocol/ActivityPub/Receiver.php on line 754
[07-Jun-2019 22:57:40 UTC] PHP Notice:  Array to string conversion in .../src/Protocol/ActivityPub/Receiver.php on line 758
```

...and in DBA.php:
```
[07-Jun-2019 22:57:40 UTC] PHP Notice:  Array to string conversion in .../src/Database/DBA.php on line 513
```

**Comment by AlfredSK** [comment]
After I pulled the latest changes (just now) my PHP error log is flooded by that:
`PHP Notice:  Undefined index: cid in /var/www/html/libranet/src/Model/Profile.php on line 325`

**Comment by MrPetovan** [comment]
> ...and in DBA.php:
> 
> ```
> [07-Jun-2019 22:57:40 UTC] PHP Notice:  Array to string conversion in .../src/Database/DBA.php on line 513
> ```

It's impossible to debug without the full trace unfortunately, since it concerns the value of an arbitrary parameter that would be defined in one of the gazillion calls to `DBA::p` throughout the app.

**Comment by copiis** [comment]
`PHP Notice:  Undefined index: inbound in /friendica/src/Protocol/PortableContact.php on line 752`

**Comment by annando** [comment]
@MrPetovan should be solved by https://github.com/friendica/friendica/pull/7267 as well.

**Comment by AlfredSK** [comment]
15-Jun-2019:
`Undefined index: edited in .../src/Protocol/Diaspora.php on line 3546`

**Comment by AlfredSK** [comment]
15-Jun-2019:
`Only variables should be passed by reference in .../src/Module/Admin/Federation.php on line 91`

**Comment by AlfredSK** [comment]
15-Jun-2019:
```
Undefined index: addr in .../src/Model/Contact.php on line 1466
Undefined index: addr in .../src/Model/Contact.php on line 1505
```

**Comment by copiis** [comment]
`PHP Notice:  Uninitialized string offset: 1 in /friendica/src/Model/Item.php on line 2474`

**Comment by copiis** [comment]
PHP Notice:  Trying to get property 'id' of non-object in /friendica/addon/twitter/twitter.php on line 1552

**Comment by MrPetovan** [comment]
> `PHP Notice: Uninitialized string offset: 1 in /friendica/src/Model/Item.php on line 2474`

There isn't any array access on this line in the current RC, what commit are you on?

**Comment by AlfredSK** [comment]
```
[19-Jun-2019 11:43:54 America/Bahia] PHP Notice:  Undefined index: wppost in .../addon/wppost/wppost.php on line 153
[19-Jun-2019 11:43:54 America/Bahia] PHP Notice:  Undefined index: wp_shortcheck in .../addon/wppost/wppost.php on line 159

```
on current RC

**Comment by AlfredSK** [comment]
And...
```
[19-Jun-2019 11:47:17 America/Bahia] PHP Notice:  Undefined index: service_class in .../mod/uexport.php on line 103
```
on current RC

**Comment by AlfredSK** [comment]
Some notices in Fetch.php

```
[21-Jun-2019 12:06:34 UTC] PHP Notice:  Undefined index: scheme in .../src/Module/Diaspora/Fetch.php on line 44
[21-Jun-2019 12:06:34 UTC] PHP Notice:  Undefined index: host in .../src/Module/Diaspora/Fetch.php on line 44
```

**Comment by AlfredSK** [comment]
...and some for tumblr.php

```
[21-Jun-2019 09:55:37 UTC] PHP Notice:  Undefined index: tumblr in .../addon/tumblr/tumblr.php on line 300
[21-Jun-2019 09:55:37 UTC] PHP Notice:  Undefined index: tumblr_bydefault in .../addon/tumblr/tumblr.php on line 302
```

**Comment by MrPetovan** [comment]
Closed for release, onwards to https://github.com/friendica/friendica/issues/7299

**Comment by copiis** [comment]
Geting this every day since a few days on -stable

```
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 228
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 256
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 320
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 333
```

**Comment by MrPetovan** [comment]
Please post it to #7299
