### ISSUE TITLE
[2019.12] PHP Notices

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#7677]
Please report here any PHP Notice message obtained running the `2019.09` stable or `2019.12-dev` versions.
Follow-up #7299 

Open issues (at least they don't have a "fixed" tag):
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-536270441 `Undefined index: id in /src/Worker/Delivery.php on line 359`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-536270657 `Undefined index: summary in .../mod/events.php on line 435`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-536270860 `Uninitialized string offset: 1 in /src/Model/Item.php on line 2536`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-536270985 `Undefined index: dob in .../mod/profiles.php on line 210`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-536271064 `Undefined index: tumblr_bydefault in .../addon/tumblr/tumblr.php on line 302`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-540554810 `Undefined index: url in /src/Worker/Notifier.php on line 438`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-541440701 `Undefined index: pubkey in /var/www/friendica/src/Protocol/ActivityPub.php on line 154`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-546417848 `Undefined index: hidewall in /var/www/friendica/src/Model/GContact.php on line 1132`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-552182832 `Uninitialized string offset: 1 in .../src/Model/Item.php on line 262`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-560090354 `Undefined index: albumname in .../mod/photos.php on line 1039`
 * [ ] https://github.com/friendica/friendica/issues/7677#issuecomment-568059733 `Undefined index: @context in .../src/Protocol/ActivityPub/Processor.php on line 583`

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-520254586
by @copiis
> develop
> 
> ```
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 359
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 413
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 215
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 243
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 316
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 329
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 215
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 243
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 316
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 329
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 215
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 243
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 316
> PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 329
> PHP Notice:  Undefined index: url in /addon/twitter/twitter.php on line 624
> ```

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-531461438
By @alfredsk
> Some 'undefined index' notices related to events:
> 
> ```
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: summary in .../mod/events.php on line 435
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: desc in .../mod/events.php on line 436
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: location in .../mod/events.php on line 437
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: id in .../mod/events.php on line 438
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: cid in .../mod/events.php on line 439
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: uri in .../mod/events.php on line 440
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: allow_cid in .../mod/events.php on line 446
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: finish in .../mod/events.php on line 459
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: adjust in .../mod/events.php on line 463
> ```

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-531553721
By @copiis
> RC
> `PHP Notice: Uninitialized string offset: 1 in /src/Model/Item.php on line 2536`

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-531557321
By @alfredsk
> RC:
> 
> ```
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: dob in .../mod/profiles.php on line 210
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: gender in .../mod/profiles.php on line 242
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: detailed_profile in .../mod/profiles.php on line 341
> ```

**Comment by nupplaphil** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-536200543
By @alfredsk
> [tumblr] on RC:
> 
> ```
> PHP Notice:  Undefined index: tumblr_bydefault in .../addon/tumblr/tumblr.php on line 302
> PHP Notice:  Undefined index: tumblr in .../addon/tumblr/tumblr.php on line 300
> ```

**Comment by AlfredSK** [comment]
2019.09:
`PHP Notice:  Undefined index: openRegistrations in .../src/Protocol/PortableContact.php on line 807`

**Comment by copiis** [comment]
2019.09```

PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 399
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 458
```

**Comment by Quix0r** [comment]
With latest develop code, I have these:
[code]Notice: Undefined index: marital in /var/www/.../mod/profiles.php on line 250
Notice: Undefined index: sexual in /var/www/.../mod/profiles.php on line 314
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 426
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 427
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 434
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 435
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 436
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 437[/code]

When I save my profile. Also martial status and sexual preference options are shown as "Array", expected is some selection box, I guess?

**Comment by Quix0r** [comment]
When attempting to drop a photo album:
[code]Notice: Undefined index: albumname in /var/www/.../mod/photos.php on line 1031
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 426
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 427
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 434
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 435
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 436
Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 437[/code]

**Comment by Quix0r** [comment]
Also the cancel button on same view is not redirecting as expecting (same view again).

**Comment by MrPetovan** [comment]
Your webserver isn't correctly configured for production use. The `Warning: Cannot modify header information - headers already sent` messages show because you chose to have all error messages directly displayed instead of written to a log file.

I would recommend disabling `display_errors` and setting up `error_log`  instead in your `php.ini`. For your last two reports, you would have gotten only the `Notice: ` message in your log file without disturbing your node usage.

**Comment by Quix0r** [comment]
I like that idea because it doesn't give information away. Yet still I see my (currently personal) instance  as a developer node and not productive. So it is fine to let these messages mess the output. Then I must directly intervene.

**Comment by MrPetovan** [comment]
Perfect since you know what you're doing! 👍

**Comment by copiis** [comment]
2019-09
`PHP Notice:  Undefined index: url in /src/Worker/Notifier.php on line 438`

**Comment by AlfredSK** [comment]
After merging PR #7725 my log is flooded with:

```
PHP Notice:  Undefined index: privkey in .../src/Core/Authentication.php on line 30
```

**Comment by MrPetovan** [comment]
On it.

**Comment by Rudloff** [comment]
I am getting this in 2019.09:
```
PHP Notice:  Undefined index: pubkey in /var/www/friendica/src/Protocol/ActivityPub.php on line 154
```

**Comment by Quix0r** [comment]
When I click on the lock icon, I get this:
`Notice: Undefined index: contact-id in /var/www/../htdocs/addon/remote_permissions/remote_permissions.php on line 77`

**Comment by AndyHee** [comment]
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Friendica\Util\Logger\WorkerLogger::debug() must be of the type array, string given, called in /var/www/friendica/src/Core/Logger.php on line 219 and defined in /var/www/friendica/src/Util/Logger/WorkerLogger.php:189
Stack trace:
#0 /var/www/friendica/src/Core/Logger.php(219): Friendica\Util\Logger\WorkerLogger->debug('Notifier entry:...', 'debug')
#1 /var/www/friendica/src/Worker/Delivery.php(281): Friendica\Core\Logger::debug('Notifier entry:...', 'debug')
#2 /var/www/friendica/src/Worker/Delivery.php(204): Friendica\Worker\Delivery::deliverDFRN('drop', Array, Array, Array, Array, true, true, false)
#3 [internal function]: Friendica\Worker\Delivery::execute('drop', 1709450, 15243)
#4 /var/www/friendica/src/Core/Worker.php(400): call_user_func_array('Friendica\\Worke...', Array)
#5 /var/www/friendica/src/Core/Worker.php(299): Friendica\Core\Worker::execFunction(Array, 'Delivery', Array, true)
#6 /var/www/friendica/src/Core/Worker.php(114): Friendica\Core\Worker::execu in /var/www/friendica/src/Util/Logger/WorkerLogger.php on line 189

**Comment by AndyHee** [comment]
Where shall I post this error?

I get numerous errors like this:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Friendica\Util\Logger\WorkerLogger::debug() must be of the type array, string given, called in /var/www/friendica/src/Core/Logger.php on line 219 and defined in /var/www/friendica/src/Util/Logger/WorkerLogger.php:189
Stack trace:
#0 /var/www/friendica/src/Core/Logger.php(219): Friendica\Util\Logger\WorkerLogger->debug('Notifier entry:...', 'debug')
#1 /var/www/friendica/src/Worker/Delivery.php(281): Friendica\Core\Logger::debug('Notifier entry:...', 'debug')
#2 /var/www/friendica/src/Worker/Delivery.php(204): Friendica\Worker\Delivery::deliverDFRN('drop', Array, Array, Array, Array, true, true, false)
#3 [internal function]: Friendica\Worker\Delivery::execute('drop', 1709450, 15243)
#4 /var/www/friendica/src/Core/Worker.php(400): call_user_func_array('Friendica\\Worke...', Array)
#5 /var/www/friendica/src/Core/Worker.php(299): Friendica\Core\Worker::execFunction(Array, 'Delivery', Array, true)
#6 /var/www/friendica/src/Core/Worker.php(114): Friendica\Core\Worker::execu in /var/www/friendica/src/Util/Logger/WorkerLogger.php on line 189
```

**Comment by MrPetovan** [comment]
It's been taken care of in the proper thread: https://github.com/friendica/friendica/issues/7675#issuecomment-542970384

**Comment by AndyHee** [comment]
Thank you kindly, @MrPetovan !

**Comment by AndyHee** [comment]
**2019.12-dev** 

```
PHP Notice:  Undefined index: hidewall in /var/www/friendica/src/Model/GContact.php on line 1127
PHP Notice:  Undefined variable: addr in /var/www/friendica/src/Model/GContact.php on line 1128
PHP Notice:  Undefined variable: addr in /var/www/friendica/src/Model/GContact.php on line 1129
```

**Comment by AndyHee** [comment]
**2019.12-dev**

```
PHP Notice:  Undefined index: hidewall in /var/www/friendica/src/Model/GContact.php on line 1132
PHP Notice:  Undefined variable: addr in /var/www/friendica/src/Model/GContact.php on line 1133
PHP Notice:  Undefined variable: addr in /var/www/friendica/src/Model/GContact.php on line 1134
```

**Comment by AlfredSK** [comment]
2019.12-dev:
`PHP Notice:  Undefined variable: hide_wall in .../mod/settings.php on line 574`

**Comment by AlfredSK** [comment]
2019.12-dev: I'm getting _a lot_ of these notices now...
`Undefined variable: savedFolderName in .../src/Content/Item.php on line 46`

Caused by #7811 

Looks like the variable $savedFolderName is defined later in Item.php (line 51).

**Comment by AlfredSK** [comment]
2019.12-dev:

`PHP Notice:  Uninitialized string offset: 1 in .../src/Model/Item.php on line 262`

**Comment by AlfredSK** [comment]
2019.12-dev:

`Undefined index: addr in .../src/Protocol/Diaspora.php on line 3453`

**Comment by AlfredSK** [comment]
2019.12-dev:
`PHP Notice:  Undefined index: hidewall in .../src/Core/ACL.php on line 413`

**Comment by AlfredSK** [comment]
2019.12-dev:
`Undefined index: albumname in .../mod/photos.php on line 1039`

Already reported [here](https://github.com/friendica/friendica/issues/7677#issuecomment-538223747) but now with the current line number.

**Comment by AlfredSK** [comment]
2019.12-dev:
`Undefined index: attach in .../src/Protocol/Diaspora.php on line 2712`

**Comment by AlfredSK** [comment]
2019.12-dev:

After updating the local code with PR #7919 I'm getting tons of...

`Undefined variable: update_contact in .../src/Model/Contact.php on line 1485`

**Comment by copiis** [comment]
`PHP Notice:  Uninitialized string offset: 1 /src/Model/Item.php on line 2624
`

**Comment by MrPetovan** [comment]
This would happen when we capture an empty tag (just `#`), which I'm not sure how it can happens without the relevant source body.

**Comment by ben-utzer** [comment]
php 7.4.0 and current release candidate 2019.12-rc:

`PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 124
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 128
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 129
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 131
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 132
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/mod/display.php on line 133
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/src/Model/Item.php on line 3781
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/src/Network/Probe.php on line 1265
 PHP Notice:  Trying to access array offset on value of type bool in /srv/www/src/Protocol/DFRN.php on line 987
 PHP Notice:  Trying to access array offset on value of type null in /srv/www/mod/display.php on line 262
 PHP Notice:  Trying to access array offset on value of type null in /srv/www/mod/display.php on line 285
 PHP Notice:  Trying to access array offset on value of type null in /srv/www/mod/display.php on line 300
 PHP Notice:  Trying to access array offset on value of type null in /srv/www/mod/display.php on line 323
 PHP Notice:  Trying to access array offset on value of type null in /srv/www/mod/salmon.php on line 70
 PHP Notice:  Undefined index: image/gif in /srv/www/mod/photos.php on line 1260
 PHP Notice:  Undefined index: image/gif in /srv/www/mod/photos.php on line 1262
`

I fixed and imagick problem yesterday, maybe the last two were caused by that problem.

**Comment by AlfredSK** [comment]
current RC:

```
Undefined index: contact_allow in .../src/Module/Item/Compose.php on line 88
Undefined index: group_allow in .../src/Module/Item/Compose.php on line 89
Undefined index: contact_deny in .../src/Module/Item/Compose.php on line 90
Undefined index: group_deny in .../src/Module/Item/Compose.php on line 91
```

**Comment by MrPetovan** [comment]
> ```
> PHP Notice:  Undefined index: image/gif in /srv/www/mod/photos.php on line 1260
> PHP Notice:  Undefined index: image/gif in /srv/www/mod/photos.php on line 1262
> ```
> 
> I fixed and imagick problem yesterday, maybe the last two were caused by that problem.

What are we supposed to do when an image type isn't supported?

**Comment by AlfredSK** [comment]
Current RC:

`PHP Notice:  Undefined variable: item in .../mod/display.php on line 259`

**Comment by AlfredSK** [comment]
Also current RC:

`Undefined property: stdClass::$screen_name in .../include/api.php on line 5306`

**Comment by AlfredSK** [comment]
Current RC as well:

`Undefined index: @context in .../src/Protocol/ActivityPub/Processor.php on line 583`

**Comment by MrPetovan** [comment]
Closed by #8000
