### ISSUE TITLE
[2020.03] PHP Notices

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8000]
Please report here any PHP Notice message obtained running the `2019.12` stable or `2020.03-dev` versions.

Follow-up to #7677 

Open issues:
- [ ] https://github.com/friendica/friendica/issues/8000#issuecomment-568800825 `Undefined index: @context in .../src/Protocol/ActivityPub/Processor.php on line 583`
- [x] https://github.com/friendica/friendica/issues/8000#issuecomment-569462713 `Undefined offset: 0 in .../src/Module/Api/Mastodon/FollowRequests.php on line 114`
- [x] https://github.com/friendica/friendica/issues/8000#issuecomment-570662635 `Undefined index: id in .../src/Protocol/Diaspora.php on line 1557`
- [x] https://github.com/friendica/friendica/issues/8000#issuecomment-574497701 `Undefined index: verb in /include/enotify.php on line 503`
- [x] https://github.com/friendica/friendica/issues/8000#issuecomment-578650437 `Undefined index: body in /src/Worker/Delivery.php on line 255`
- [x] https://github.com/friendica/friendica/issues/8000#issuecomment-578650437 `Undefined offset: 0 in /src/Protocol/DFRN.php on line 511`

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-531461438
By @alfredsk
> Some 'undefined index' notices related to events:
> 
> ```
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: summary in .../mod/events.php on line 435
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: desc in .../mod/events.php on line 436
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: location in .../mod/events.php on line 437
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: id in .../mod/events.php on line 438
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: cid in .../mod/events.php on line 439
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: uri in .../mod/events.php on line 440
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: allow_cid in .../mod/events.php on line 446
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: finish in .../mod/events.php on line 459
> [14-Sep-2019 06:45:09 UTC] PHP Notice:  Undefined index: adjust in .../mod/events.php on line 463
> ```

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-531557321
By @alfredsk
> RC:
> 
> ```
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: dob in .../mod/profiles.php on line 210
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: gender in .../mod/profiles.php on line 242
> [15-Sep-2019 10:00:25 Europe/Berlin] PHP Notice:  Undefined index: detailed_profile in .../mod/profiles.php on line 341
> ```

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7299#issuecomment-536200543
By @alfredsk
> [tumblr] on RC:
> 
> ```
> PHP Notice:  Undefined index: tumblr_bydefault in .../addon/tumblr/tumblr.php on line 302
> PHP Notice:  Undefined index: tumblr in .../addon/tumblr/tumblr.php on line 300
> ```

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7677#issuecomment-538200370

By @Quix0r

> With latest develop code, I have these:
> 
> ```
> Notice: Undefined index: marital in /var/www/.../mod/profiles.php on line 250
> Notice: Undefined index: sexual in /var/www/.../mod/profiles.php on line 314
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 426
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 427
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 434
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 435
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 436
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/profiles.php:250) in /var/www/.../src/App/Page.php on line 437
> ```
> 
> When I save my profile. Also martial status and sexual preference options are shown as "Array", expected is some selection box, I guess?

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7677#issuecomment-538223747

By @Quix0r

> When attempting to drop a photo album:
> 
> ```
> Notice: Undefined index: albumname in /var/www/.../mod/photos.php on line 1031
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 426
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 427
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 434
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 435
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 436
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/.../mod/photos.php:1031) in /var/www/.../src/App/Page.php on line 437
> ```

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7677#issuecomment-541440701

By @Rudloff

> I am getting this in 2019.09:
> 
> ```
> PHP Notice:  Undefined index: pubkey in /var/www/friendica/src/Protocol/ActivityPub.php on line 154
> ```

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/issues/7677#issuecomment-568059733

By @AlfredSK

> Current RC as well:
> 
> `Undefined index: @context in .../src/Protocol/ActivityPub/Processor.php on line 583`

@annando I'm not sure what to do with the missing `@context`.

**Comment by AlfredSK** [comment]
2019.12 master:

`Undefined offset: 0 in .../src/Module/Api/Mastodon/FollowRequests.php on line 114`

**Comment by AlfredSK** [comment]
2020.03-dev:

I'm getting huge amounts of the following notices after pulling https://github.com/friendica/friendica-addons/pull/935

```
PHP Notice:  Undefined property: Friendica\App::$page in .../addon/openstreetmap/openstreetmap.php on line 60
PHP Notice:  Undefined index: htmlhead in .../addon/openstreetmap/openstreetmap.php on line 60
```

**Comment by AlfredSK** [comment]
2020.03-dev:

`[31-Dec-2019 16:38:55 UTC] PHP Notice:  Undefined index: baseurl in .../src/DI.php on line 86`

**Comment by AlfredSK** [comment]
202.03-dev:

`[31-Dec-2019 16:56:21 UTC] PHP Notice:  Object of class Friendica\App\BaseURL could not be converted to int in .../src/Module/Objects.php on line 40`

**Comment by AlfredSK** [comment]
Tumblr / 2020.03-dev:

`PHP Notice:  session_start(): A session had already been started - ignoring in .../addon/tumblr/tumblr.php on line 102`

Happens together with the fatal error I reported.

**Comment by AlfredSK** [comment]
2020.03-dev

`PHP Notice:  Undefined index: fetch_further_information in .../src/Protocol/Feed.php on line 463`

**Comment by AlfredSK** [comment]
2020.03-dev:

```
PHP Notice:  Undefined index: id in .../src/Protocol/Diaspora.php on line 1557
PHP Notice:  Undefined index: url in .../src/Protocol/Diaspora.php on line 1836
PHP Notice:  Undefined index: url in .../src/Protocol/Diaspora.php on line 1837
```

**Comment by ben-utzer** [comment]
Some notices from today:

`PHP Notice:  Trying to access array offset on value of type bool in /http/www/include/api.php on line 2847
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/include/api.php on line 2848
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/include/api.php on line 5036
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/include/api.php on line 5056
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/src/Protocol/DFRN.php on line 988
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/src/Protocol/DFRN.php on line 989
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/src/Protocol/OStatus.php on line 2086
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/src/Protocol/OStatus.php on line 2087
 PHP Notice:  Trying to access array offset on value of type bool in /http/www/src/Protocol/OStatus.php on line 239
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/api.php on line 323
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/api.php on line 330
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/api.php on line 5036
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/api.php on line 5056
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/conversation.php on line 504
 PHP Notice:  Trying to access array offset on value of type null in /http/www/include/conversation.php on line 518
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/cal.php on line 113
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/cal.php on line 127
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/cal.php on line 129
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/display.php on line 105
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 31
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 33
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 34
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 36
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 37
 PHP Notice:  Trying to access array offset on value of type null in /http/www/mod/noscrape.php on line 45
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Content/Widget.php on line 309
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Content/Widget.php on line 427
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Model/Item.php on line 3652
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Model/Profile.php on line 906
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 111
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 113
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 117
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 118
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 119
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 120
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 121
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 166
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 170
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 171
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 172
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 182
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 190
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 192
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 195
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 196
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 199
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 222
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 285
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 287
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 329
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 358
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 87
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Module/Profile.php on line 88
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Protocol/Feed.php on line 197
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Protocol/Feed.php on line 206
 PHP Notice:  Trying to access array offset on value of type null in /http/www/src/Protocol/Feed.php on line 445`

**Comment by copiis** [comment]
develop
```
PHP Notice:  Undefined index: verb in /include/enotify.php on line 503
PHP Notice:  Undefined index: otype in /include/enotify.php on line 504
```
```

**Comment by copiis** [comment]
2019.12
```
PHP Notice:  Undefined index: body in /src/Worker/Delivery.php on line 255
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 261
PHP Notice:  Undefined offset: 0 in /src/Protocol/DFRN.php on line 511
PHP Notice:  Undefined offset: 0 in /src/Protocol/DFRN.php on line 511
PHP Notice:  Undefined offset: 0 in /src/Protocol/DFRN.php on line 511
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 289
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 370
PHP Notice:  Undefined index: id in /src/Worker/Delivery.php on line 383
```

**Comment by AlfredSK** [comment]
Frequency of this notice: ~1.5/sec. :-)

`Undefined variable: nickname in .../src/Module/NoScrape.php on line 36`

**Comment by AlfredSK** [comment]
2020.03-dev:

```
Undefined index: fromName in .../addon/phpmailer/phpmailer.php on line 65
Undefined index: messageSubject in .../addon/phpmailer/phpmailer.php on line 72
Undefined index: textVersion in .../addon/phpmailer/phpmailer.php on line 85
```

**Comment by AlfredSK** [comment]
I upgraded to **PHP 7.4** because I was bored getting so few notices. Now I'm getting tons of notices. :-)
This is a follow-up report to https://github.com/friendica/friendica/issues/8000#issuecomment-573883153

This is from a 2-minute snapshot piped through sort and uniq:

```
Trying to access array offset on value of type bool in .../src/Model/UserItem.php on line 62
Trying to access array offset on value of type null in .../include/conversation.php on line 497
Trying to access array offset on value of type null in .../include/conversation.php on line 511
Trying to access array offset on value of type null in .../src/Content/Widget.php on line 337
Trying to access array offset on value of type null in .../src/Content/Widget.php on line 454
Trying to access array offset on value of type null in .../src/Model/Item.php on line 3658
Trying to access array offset on value of type null in .../src/Module/BaseProfile.php on line 26
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 39
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 41
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 42
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 44
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 45
Trying to access array offset on value of type null in .../src/Module/NoScrape.php on line 53
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 117
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 143
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 145
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 187
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 215
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 32
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 36
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 37
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 38
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 39
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 71
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 75
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 76
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 77
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 84
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 86
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 88
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 91
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 92
Trying to access array offset on value of type null in .../src/Module/Profile/Status.php on line 95
Trying to access array offset on value of type null in .../view/theme/vier/theme.php on line 30
```

**Comment by MrPetovan** [comment]
Oh yeah, we were bored to fix language compatibility issues as well.

**Comment by AlfredSK** [comment]
I'm sorry.

**Comment by AlfredSK** [comment]
2020.03-dev / PHP 7.2:

```
Undefined offset: 0 in .../src/Module/Api/Mastodon/FollowRequests.php on line 109
Trying to get property 'id' of non-object in .../src/Module/Api/Mastodon/FollowRequests.php on line 109
```

**Comment by AlfredSK** [comment]
2020.03-dev

`Undefined index: query in .../src/Content/BoundariesPager.php on line 61`

**Comment by AlfredSK** [comment]
After pulling the new 'disable dislikes' feature...
`Undefined index: dislike in .../include/conversation.php on line 1591`

**Comment by AlfredSK** [comment]
```
Undefined index: name in .../src/Module/Contact/Hovercard.php on line 103
Undefined index: nick in .../src/Module/Contact/Hovercard.php on line 104
Undefined index: addr in .../src/Module/Contact/Hovercard.php on line 105
Undefined index: url in .../src/Module/Contact/Hovercard.php on line 105
Undefined index: thumb in .../src/Module/Contact/Hovercard.php on line 106
Undefined index: url in .../src/Module/Contact/Hovercard.php on line 107
Undefined index: nurl in .../src/Module/Contact/Hovercard.php on line 108
Undefined index: location in .../src/Module/Contact/Hovercard.php on line 109
Undefined index: about in .../src/Module/Contact/Hovercard.php on line 110
Undefined index: network in .../src/Module/Contact/Hovercard.php on line 111
Undefined index: url in .../src/Module/Contact/Hovercard.php on line 111
Undefined index: keywords in .../src/Module/Contact/Hovercard.php on line 112
Undefined index: birthday in .../src/Module/Contact/Hovercard.php on line 113
```

**Comment by AlfredSK** [comment]
2020.03-dev

`Undefined offset: 1 in .../src/Core/Theme.php on line 102`

Happens when visiting .../admin/themes.

**Comment by AlfredSK** [comment]
`Undefined index: link in .../src/Model/Item.php on line 3873`

**Comment by AlfredSK** [comment]
2020.03-rc

`Undefined index: aliases in .../src/Network/Probe.php on line 373`

**Comment by AlfredSK** [comment]
2020.03-rc

`Undefined index: type in .../src/Protocol/ActivityPub/Processor.php on line 482`

**Comment by AlfredSK** [comment]
2020.03-rc
`Undefined index: internal-psid in .../src/Model/Item.php on line 330`

**Comment by AlfredSK** [comment]
2020.03-rc
```
Undefined index: photo in .../src/Module/Search/Acl.php on line 83
Undefined index: name in .../src/Module/Search/Acl.php on line 84
Undefined index: addr in .../src/Module/Search/Acl.php on line 85
Undefined index: url in .../src/Module/Search/Acl.php on line 85
Undefined index: network in .../src/Module/Search/Acl.php on line 86
Undefined index: url in.../src/Module/Search/Acl.php on line 87
```

**Comment by AlfredSK** [comment]
2020.03-rc:

`PHP Notice: Undefined index: object in .../src/Module/Objects.php on line 66`

**Comment by AlfredSK** [comment]
2020.03-rc:

`Undefined index: object in .../src/Protocol/ActivityPub/Transmitter.php on line 199`

**Comment by MrPetovan** [comment]
Closed by #8475
