### ISSUE TITLE
[Discussion] UI improvement

### ISSUE THREAD

**Issue by Extarys** [friendica/friendica#9787]
I'm new to friendica but I'm trying to convince some friends to ditch faceb00k or at least also have an account on the fediverse, but the overall experience is less optimal than big corpos social media right now - they say it feels less approachable. I want to address that the best I can. I'm mainly on matrix and I don't have a friendica instance yet (I should probably register an account somewhere in the meantime).

I want to gather community feedback on theming. I want to concentrate on the frio theme and maybe create another theme if I see I can't make frio more user friendly without changing it too much.

If you have anything that is bothering you or little quirks, I suggest we discuss this here. I'll keep track of the feedbacks and try to implement them. This is also for me to follow/track what UI/UX issues needs to be addressed.

**Frio:**
- [x] Make tags colors less intrusive (#7557)
- [ ] Able to create a post from any page
- [ ] Quick way to change viewing permission (public, friends, only me) before posting
- [x] More readable font? [#9769] Maybe as a server setting
- [x] Mobile dark theme doesn't work on left side bar [#9764]
- [x] Mobile top bar icons not aligned [#9761]
- [x] UX - Better way to block user [#9719]
- [ ] Emoji picker [#9298]
- ~~[ ] back-to-top button doesn't appear as expected~~ [#9791]
- [ ] Implement a guided tour - New user ease to get to know friendica [#9185]
- [ ] Better linking and communication with user on other instances [#8547]
- [ ] Mobile: information regarding source of the post [#9258]
- [ ] mobile: improve navbar icons, center/highlight
- [x] mobile: dark: right sidebar background doesn't respect color scheme [#9811]
- [ ] frio: mobile: shared posts use very bright highlighting line [#9839]
- [ ] frio: mobile: reduce double lines to single line as post separator [#9838]
- [ ] frio: mobile: inconsistent sidebars [#9837, #9812]
- [ ] frio: Multilanguage posting [#6043]

**Create another theme? (What could we do differently?)**

- Implement JOSE-type tokens for client-side rendering #9813

**Not frio, but still**
- [x] Merge frio-specific share block template into the base template [#9378] **2021.03**
- [ ] Drag and drop/paste photos to share (post, comments, private messages) [#8848 #8674 #8580]
  - Blocked by #9824
- [ ] Better friend request options [#9714]
- [ ] To fix: I can both like and dislike the same post
- [ ] Improve notification [#9729 and #8247]
- [ ] Improve action tooltips to explain contact actions to users [#9774] (Could be worked with "guided tour" above)
- [ ] Vier: Clicking on sandwich in mobile Vier in contacts view redirects to main page instead of showing sidebar #9809 

**Other ideas worth discussing - UX/UI**
Those may need an issue on their own, but I don't want to forget about them so...

- Embed a hydrogen/matrix chat directly in friendica (faceb00k like). Could replace the `Message` page if the server owner also have a matrix instance. We would need a way to create both a friendica account and a matrix account on account creation (accounts!!) [May need an issue on it's own for more discussion?]
- When sharing a video, upload automatically to a peertube instance and embed it into the post. If a peertube instance is set, maybe allow users to go live directly in friendica? #9785

**Comment by MrPetovan** [comment]
Thank you for opening this issue. I would like to very strongly discourage the creation of a new theme. I'm not sure how @rabuzarus pulled this off mostly on his own for Frio, but we're probably looking at several hundred hours of work to create a new working consistent theme for Friendica. Most of the current themes have been variations of the initial one, with Frio being the latest notable and welcome exception.

I took the liberty of moving the issues you weren't sure were frio-specific in the appropriate categories.

> * Embed a hydrogen/matrix chat directly in friendica (faceb00k like). Could replace the `Message` page if the server owner also have a matrix instance. We would need a way to create both a friendica account and a matrix account on account creation (accounts!!) [May need an issue on it's own for more discussion?]

We've had an xmpp chat integration that was using the Friendica credentials, but it's been unreliable and I don't know if there's a remaining working example of it anymore.

**Comment by Extarys** [comment]
> but we're probably looking at several hundred hours of work to create a new working consistent theme for Friendica

I know, I can't believe how hard it is (I played with the idea yesterday, hot damn!)

I made a [post on the forum](https://nerdica.net/display/a85d7459-2160-01aa-69e6-add608831768) about it but I'll say it here to keep track. I'm more familiar with vuejs and it would require way less time to make a theme if we wouldn't need to rely on php to inject code and all (not good with some technical terms, sorry). If there is an api endpoint or a way to use/implement vuejs instead of smarty it might be easier to make a theme and make the experience more responsive. Since each component and pages can have it's own javascript and style it makes the overall maintenance effort quite lower.

VueJS make it so easy to add/remove components and is fast (both in development and execution). I will continue to investigate this.

> I took the liberty of moving the issues you weren't sure were frio-specific in the appropriate categories.

Thank you! :smiling_face_with_three_hearts: 

> We've had an xmpp chat integration that was using the Friendica credentials, but it's been unreliable and I don't know if there's a remaining working example of it anymore.

I thought about it before writing that. Using vuejs, this would be easier to implement. Someone would still need to write codes to tie both, etc but still. I might add an emoji picker and my only thought was how easy this would be with vuejs lol

I want to note that my main focus will be on improving Frio (and on the side, finding a way to make a VueJS interface)

**Comment by MrPetovan** [comment]
Now, while a new theme is probably out of reach, a VueJS frontend is entirely viable. Friendica exposes several API endpoint that a rich client can leverage: https://friendica.mrpetovan.com/help/api

And if any is missing, adding new API endpoints is way less expensive development-wise than new templates/modules.

**Comment by SpencerDub** [comment]
> Emoji picker

I would _love_ to see this (and a Mastodon-like interface for adding custom emoji in the admin interface). I even wrote (amateur) project descriptions for both parts there (picker and admin interface) for a friend who said he might have some time to develop it... but then 2020 happened, and it went nowhere.

I don't have the chops to make it myself, but consider this a very strong +1 for an emoji picker/admin interface, if anyone who has the know-how and time to do it is looking for encouragement.

Some of the resources I dug up while making my project description that may be useful for someone working on this:

* [Emoji Mart](https://github.com/missive/emoji-mart) - The emoji picker used in Mastodon. Supports default Unicode emoji and custom smileys. Licensed under BSD.
* [mastodon/.../emoji_picker_dropdown.js](https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/compose/components/emoji_picker_dropdown.js) - From what I can tell, this is Mastodon's implementation of Emoji Mart. I could be wrong, though--this is fairly out of my league.
* [smileybutton](https://github.com/friendica/friendica-addons/tree/develop/smileybutton) - An existing addon for Friendica that displays all custom smileys installed on a node, accessible via a button in the post composer. Has some issues:
    1. Clicking smileys doesn't appear to do anything
    2. The smiley button in the post composer is out of alignment with other icons, is too large, is displayed in black instead of `#555` grey like other icons, and doesn't display a pointer icon or have a shaded background on hover.
    3. Doesn't display standard Unicode emoji
    4. Smileys are not organized in any apparent way
    5. Smileys are not searchable

**Comment by Extarys** [comment]
@SpencerDub Thanks for your comment. I'm still not familiar with how everything works for friendica (injecting js and static tpl files) but I started - that is a strong word - I was able to add a js file and make a call from the "write post" modal :laughing: so that's a start.

I didn't spend much time on this today but I'm taking a look.

EDIT: Emoji Mart! :facepalm: that is what Matrix Element is using. Thanks, I searched for that an whole hour today and couldn't find it.

**Comment by MrPetovan** [comment]
Do not hesitate to reach out if you have technical questions. I'm available on here or in Friendica, in public messages (through [the Friendica Developers forum](https://forum.friendi.ca/profile/developers)) or private messages directly.

**Comment by xundeenergie** [comment]
We discussed a few weeks ago also the second issue in the list 

> Able to create a post from any page

The discussion you can finde here https://soc.schuerz.at/display/4edd2508-1062-2a60-c13c-c56366142533

There are different usecases and improvements.

First, a new "Post"-Interface is needed. The user should be able to choose, where it want to post. Posting to a forum, to the public timeline, another group... the best choice seems to be a dropdown with search-function above the text/subject for the posting. 
If I'm in a group, this group should be default choosen, when clicking to the "create post"-button. 
Multiple Choises should be possible for more than one group/destination.

For me it seems a good idea, to have this posting-creation-dialog at the top of the visible timeline. Each timeline! /network /community/local /community/global and so on.

Posting to a group/forum should not contain the mention with @ or !. It should happen only via meta-data-field (choosen by the dropdown for the destination.)

On profile-view there should be also a button to create a posting, where the viewed user get mentioned. 
Another button for private message to this user directly.

And the display of groups is annoying... Viewing it from the contact list, i can not create a posting to the group. 
Viewing it from the widget shows other information... 

In Group/Forum-Widget it should be possible, to sort the list and make groups/forums to favorits - showing first. 

### Picture Upload is also a very annoying topic in friendica. It's so annoying, that i can not recommend friendica to my friends... 

Upload via Drag&Drop and Copy&Paste must be possible!!! 

My ideas:
When i upload an Image to a posting, it should appear at the bottom of the creation-dialog with a button beside to insert this image into the text at cursor-position.
So i can upload one or more images for THIS posting and choose after the upload, where i want to insert it into the text. 

The creation-Dialog must be THE SAME as on create a comment. I had the experience that i start to write a comment. Then i had the idea to add an image, clicked on the button to add images... got lead to the other dialog to upload my images... and the text was lost... annoying.
